Add GitHub Actions build
Pryaxis/TShock pull request #1681
Opened 2019-10-02 21:11 UTC by sgkoishi

Fix the build script and add the badge to the readme.

2019-10-02 21:43 UTC, hakusaro requested changes
Thank you so so much! I really appreciate this. Can you address the one comment? If we went forward with this, we would actually love to have artifact downloading as part of GitHub actions CI, possibly to just eliminate AppVeyor/Travis entirely, too. If you can't do that, that's okay, but it would be an awesome add.

According to the docs, I think msbuild should actually be included in the virtual environment actions uses on windows? I could be entirely wrong, but it might be worth checking to see if you need to install it.

2019-10-02 21:43 UTC, hakusaro commented on .github/workflows/msbuild-test.yml
> +      run: powershell "$source = (New-Object System.Net.WebClient).DownloadString(\"https://gist.githubusercontent.com/sgkoishi/87e613881f9164bf03849603dd4f4266/raw/\") ; Add-Type
Can you add this script to the repo itself? We can't really link to a random gist from inside this repo for security purposes.

2019-10-02 23:42 UTC, sgkoishi commented
> 
> 
> Thank you so so much! I really appreciate this. Can you address the one comment? If we went forward with this, we would actually love to have artifact downloading as part of GitHub actions CI, possibly to just eliminate AppVeyor/Travis entirely, too. If you can't do that, that's okay, but it would be an awesome add.
> 
> According to the docs, I think msbuild should actually be included in the virtual environment actions uses on windows? I could be entirely wrong, but it might be worth checking to see if you need to install it.

I've added the gist to repo, and the artifact is already included. ([example](https://github.com/sgkoishi/TShock/runs/245623098)) ([code](https://github.com/Pryaxis/TShock/pull/1681/commits/79b092b9c13e21df684f342708ef0f74bb72cd4e#diff-df91aecff22f5180353b36928fc4042aR38-R41))

MSBuild: I'm not quite sure if there is a msbuild in the environment - but at least it's not in the PATH environment variable. NuGet is also required since all these projects use `packages.config` file instead of `PackageReference` in csproj, which msbuild could not handle it.

2019-10-02 23:44 UTC, sgkoishi commented on .github/workflows/msbuild-test.yml
> +      run: powershell "$source = (New-Object System.Net.WebClient).DownloadString(\"https://gist.githubusercontent.com/sgkoishi/87e613881f9164bf03849603dd4f4266/raw/\") ; Add-Type
[Updated](https://github.com/Pryaxis/TShock/pull/1681/commits/fdbc958b3481680f3ca575e9c24fe4debb100597#diff-24fc619a40b157250cc2bc1b212b4689).

2019-10-02 23:50 UTC, hakusaro commented
> I've added the gist to repo, and the artifact is already included. (example) (code)

Thank you so, so much! I totally just didn't see it. :D

2019-10-02 23:51 UTC, hakusaro approved these changes
![lgtm_6](https://user-images.githubusercontent.com/532647/66089588-d8cec380-e534-11e9-9b85-d4bdf4b07972.gif)

2019-10-02 23:53 UTC, hakusaro commented
@sgkoishi actually, before I forget: if you want, you can update the name + file to something like "Build Server" or something. It doesn't need to be called `MSBuild Test` because it works thanks to you :)

2019-10-03 04:00 UTC, QuiCM commented
LGTM :)

2019-10-03 13:39 UTC, merged

2019-10-03 13:40 UTC, hakusaro commented
@all-contributors please add @sgkoishi for code, infra

2019-10-03 14:46 UTC, hakusaro commented
@sgkoishi I'm sure you're very well aware, but [hacktoberfest](https://hacktoberfest.digitalocean.com/) is happening and you definitely deserve to be rewarded.