Fix for Vortex armor set stealth flicker bug...again
Pryaxis/TShock pull request #1685
Opened 2020-01-10 22:57 UTC by moisterrific

tests on my end showed it fixed, plz confirm as well

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????
?????? HAVE YOU UPDATED THE CHANGELOG? ??????

2020-01-13 06:52 UTC, hakusaro commented
I don't see any problem with the logic change. Can @Pryaxis/tshock review?

2020-01-13 09:08 UTC, sr229 requested changes

2020-01-13 09:08 UTC, sr229 commented on TShockAPI/GetDataHandlers.cs
> +			else
Adding an `else` does not change anything. If I understood the code right, `args.TPlayer.vertexStealthActive` will be falsey by default without it already.

2020-01-13 12:30 UTC, Ijwu commented on TShockAPI/GetDataHandlers.cs
> +			else
It does guarantee that a player sending this packet with this toggle off will be uncloaked. No telling what would affect `vertexStealthActive` in the meantime due to it referencing the player object living elsewhere.

I don't see a problem with this inherently since it just 'ties up a loose end' so to say.

2020-01-13 12:31 UTC, Ijwu commented
Does LGTM.

2020-01-13 14:14 UTC, QuiCM commented
I will perform a before/after play test of this to confirm it resolves the issue, once my schedule allows. By this weekend at the latest

2020-01-13 14:15 UTC, sr229 approved these changes

2020-01-13 21:57 UTC, Ijwu approved these changes

2020-01-13 21:57 UTC, Ijwu commented
While changes are approved, merging is pending manual QA verification.

2020-01-19 06:06 UTC, QuiCM commented
Seems to work 👍

2020-01-19 06:07 UTC, merged