Optimize workflow
Pryaxis/TShock pull request #1880
Opened 2020-05-24 04:03 UTC by sgkoishi

Overall time halved. Not a big change so no changelog update :)
* Use official NuGet installer (choco takes two minutes to download NuGet)
* Add names for tasks
* Re-order tasks

2020-05-24 04:38 UTC, hakusaro reviewed
Do not merge without approval from me -- need time to review/consider.

2020-05-24 05:19 UTC, hakusaro submitted a review, later dismissed
I think you could probably get by with changing it so we use the official nuget installer action and softcoding the path to VS, but I'm not convinced that reordering this or shifting to PowerShell for the build is necessary. I'm the one who has to maintain the build infra and while the current script is definitely not super optimized, I wouldn't say that it bothers me in the slightest and the organization is simple.

2020-05-24 05:19 UTC, hakusaro commented on .github/workflows/build.yml
> +    - name: Build TShock (Release)
We intentionally don't ever say the word "release" in this process because we don't want to convey that it is a _release_. That's why we say "not debug" and "debug."

2020-05-24 05:19 UTC, hakusaro commented on .github/workflows/build.yml
> +      shell: pwsh
I really don't want to use Powershell for this. Powershell isn't platform agnostic even when it tries to be. If we want to later switch to linux (which we might, I'd want to switch back).

2020-05-24 05:19 UTC, hakusaro commented on .github/workflows/build.yml
> +    - name: Prepare packaging
Why?

2020-05-24 05:19 UTC, hakusaro commented on .github/workflows/build.yml
> +    - name: Upload TShock (Release)
Same on the "Release" verbiage.

2020-05-24 05:19 UTC, hakusaro commented on .github/workflows/build.yml
> +    - name: Upload OTAPI Bootstrapper (Release)
Same thing here too

2020-05-24 06:29 UTC, sgkoishi commented on .github/workflows/build.yml
> +      shell: pwsh
I'm using Powershell here to put MSBuild's folder into `PATH` environment variable - so that we can replace the long `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"` with `MSBuild`. I can switch it back if you want.

2020-05-24 06:36 UTC, sgkoishi commented on .github/workflows/build.yml
> +    - name: Build TShock (Release)
Get it, replaced with `Not Debug`

2020-05-24 06:42 UTC, sgkoishi commented on .github/workflows/build.yml
> +    - name: Prepare packaging
Well I guess this is still not the *release*? ~~We need better text for this!!!~~

2020-05-24 07:21 UTC, hakusaro commented on .github/workflows/build.yml
> +    - name: Prepare packaging
Technically we made this only to prepare for releases ;)

2020-05-24 07:40 UTC, sgkoishi commented on .github/workflows/build.yml
> +    - name: Prepare packaging
Get it.

2020-05-30 07:06 UTC, hakusaro reviewed
I think this is mostly good to go. I have been thinking about this. Do you have opinions about splitting into two workflow files (one for debug mode, one for release mode)? It might result in faster stuff since the job would complete faster?

2020-05-30 21:05 UTC, sgkoishi commented
> 
> 
> I think this is mostly good to go. I have been thinking about this. Do you have opinions about splitting into two workflow files (one for debug mode, one for release mode)? It might result in faster stuff since the job would complete faster?

Splitting them will restore packages twice, but it should still be faster (like two 80-seconds vs. one 120-seconds).
There are 15 jobs in the single workflow which is kinda long. I would prefer splitting them into two 9-jobs workflows (still not short, but more acceptable).

2020-05-30 21:19 UTC, sgkoishi commented
Hmmm... Using build matrix syntax instead of splitting into two files. 
There is still a `Release` in the name of run, but all artifacts are `not debug`. Is that acceptable?

2020-05-30 21:29 UTC, hakusaro requested changes
This is looking great, but it looks like some artifacts aren't getting uploaded: 
![Screen Shot 0002-05-30 at 14 28 28](https://user-images.githubusercontent.com/532647/83339359-e4b88400-a281-11ea-9714-57f1e2a0b7fb.png)

2020-05-30 21:52 UTC, sgkoishi commented
> 
> 
> This is looking great, but it looks like some artifacts aren't getting uploaded:
> ![Screen Shot 0002-05-30 at 14 28 28](https://user-images.githubusercontent.com/532647/83339359-e4b88400-a281-11ea-9714-57f1e2a0b7fb.png)

Aha yeah, because the build configurations are `Debug` and `Release` while artifacts' names are `debug` and `not debug`.

Currently, it's trying to upload 8 artifacts (`debug`/`not debug`, TShock/OTAPI, `Debug`/`Release`), and half is empty so finally 4 artifacts will be uploaded.

Splitting them into two workflow files will fix that (with much more duplicated code).

2020-05-30 22:16 UTC, hakusaro requested changes
> `The workflow is not valid. .github/workflows/build.yml (Line: 44, Col: 11): Unexpected symbol: '"Debug"'. Located at position 16 within expression: matrix.mode == "Debug",.github/workflows/build.yml (Line: 50, Col: 11): Unexpected symbol: '"Debug"'. Located at position 16 within expression: matrix.mode == "Debug"`

Looks syntactically sad :(

2020-05-30 22:24 UTC, sgkoishi commented
No idea why they accept only `'Debug'` but no `"Debug"` :(

2020-05-30 22:56 UTC, hakusaro approved these changes
Last change before we can merge this!

2020-05-30 22:56 UTC, hakusaro commented on .github/workflows/build.yml
> +    - name: Installer NuGet client
```suggestion
    - name: Install NuGet client
```

2020-05-30 23:10 UTC, hakusaro approved these changes

2020-05-30 23:21 UTC, merged