Handlegolfpacket
Pryaxis/TShock pull request #1968
Opened 2020-06-01 11:01 UTC by Patrikkk

Added LandGolfBallInCup event which is accessible for developers to work with, as well as LandGolfBallInCup handler to handle exploits where players could send direct packets to trigger and imitate golf ball cup landing anywhere in the game world. Added two public lists in Handlers.LandGolfBallInCupHandler: GolfBallProjectileIDs and GolfClubItemIDs.

2020-06-01 14:47 UTC, Patrikkk commented on TShockAPI/Handlers/LandGolfBallInCupHandler.cs
> +				TShock.Log.ConsoleError($"LandGolfBallInCupHandler: Packet is spoofing to be player ID {args.PlayerIndex}! - From [{args.Player.Index}]{args.Player.Name}");
Should these be ConsoleDebug instead?

2020-06-02 00:29 UTC, QuiCM requested changes

2020-06-02 00:29 UTC, QuiCM commented on TShockAPI/Handlers/LandGolfBallInCupHandler.cs
> +				TShock.Log.ConsoleError($"LandGolfBallInCupHandler: Packet is spoofing to be player ID {args.PlayerIndex}! - From [{args.Player.Index}]{args.Player.Name}");
Yep.
You can also be less formal with ConsoleDebug messages because the intention is that we ask people to send specific sections of their log to capture specific messages.
I'd suggest a rephrasing to something like `LandGolfBallInCup rejected for ID spoofing. Expected {playerId} , received {actualId} from {player}`

2020-06-02 08:22 UTC, Patrikkk commented on TShockAPI/Handlers/LandGolfBallInCupHandler.cs
> +				TShock.Log.ConsoleError($"LandGolfBallInCupHandler: Packet is spoofing to be player ID {args.PlayerIndex}! - From [{args.Player.Index}]{args.Player.Name}");
Sounds, good  thanks! I sometimes have a hard time with wording when I'm coding. Will send a commit soon.

2020-06-02 09:46 UTC, QuiCM approved these changes

2020-06-02 10:04 UTC, merged