Emojipacketevent
Pryaxis/TShock pull request #1969
Opened 2020-06-01 13:25 UTC by Patrikkk

This is received from the client when they are trying to display an emoji, this comes into the server, gets processed, and the server sends back the Emote Bubble packet to the clients.

I know, this is not something important, but I'm going through the new packets one by one and adding events developers can work with, patching exploits, and thought this could be a core permission.

2020-06-01 14:47 UTC, Patrikkk commented on TShockAPI/Handlers/EmojiHandler.cs
> +				TShock.Log.ConsoleError($"EmojiHandler: Packet is spoofing to be player ID {args.PlayerIndex}! - From [{args.Player.Index}]{args.Player.Name}");
Should I change this to ConsoleDebug instead?

2020-06-02 00:27 UTC, QuiCM requested changes
Minor nitpicks and phrasing. Overall looks good

2020-06-02 00:27 UTC, QuiCM commented on TShockAPI/Handlers/EmojiHandler.cs
> +				TShock.Log.ConsoleError($"EmojiHandler: Packet is spoofing to be player ID {args.PlayerIndex}! - From [{args.Player.Index}]{args.Player.Name}");
Yep.
You can also be less formal with ConsoleDebug messages because the intention is that we ask people to send specific sections of their log to capture specific messages.
I'd suggest a rephrasing to something like `Emoji packet rejected due to ID spoofing. Expected {playerId}, received {actualId} from {player}`

2020-06-02 00:27 UTC, QuiCM commented on TShockAPI/Handlers/EmojiHandler.cs
> +		public void OnEmoji(object sender, GetDataHandlers.EmojiEventArgs args)
My preference for naming here would be `OnReceiveEmoji`, but I may add some frameworking around the `Handlers` namespace and revisit this

2020-06-02 00:27 UTC, QuiCM commented on TShockAPI/Handlers/EmojiHandler.cs
> +	/// Handles an exploit and checks for permissions.
This could be more informative.
`Handles emoji packets and checks for validity and permissions` perhaps?

2020-06-02 00:27 UTC, QuiCM commented on TShockAPI/Handlers/EmojiHandler.cs
> +				args.Player.SendErrorMessage("You have no permission to send emotes!");
I believe our normal verbiage is `You do not have permission to ...`

2020-06-02 09:26 UTC, QuiCM approved these changes

2020-06-02 09:26 UTC, merged