Permission added to REST Server Broadcast .
Pryaxis/TShock pull request #2219
Opened 2021-02-08 11:28 UTC by TheBambino

Nub trying this again.

**Feature:**
If a REST token is breached, there could be potential spam issues. Where each token perm could pose a potential risk, not having perms on ServerBroadcast makes it an issue if any token is breached. It also gives more control over those that have access to the token.

2021-02-08 14:17 UTC, bartico6 requested changes
LGTM once the comments are addressed.

Also, should determine if this was intended behaviour or not.

2021-02-08 14:17 UTC, bartico6 commented on TShockAPI/Rest/RestPermissions.cs
> +		[Description("REST user can turn off / restart the server.")]
Wrong description? :p

2021-02-08 14:18 UTC, TheBambino commented on TShockAPI/Rest/RestPermissions.cs
> +		[Description("REST user can turn off / restart the server.")]
Yes, I caught that earlier. Changing it now

2021-02-08 14:27 UTC, TheBambino commented
> LGTM once the comments are addressed.

Done.

2021-02-08 15:24 UTC, bartico6 approved these changes
While I can't accept PRs (nor do my reviews mark it as ready for merge), I'll say that everything looks good now

2021-02-21 01:25 UTC, hakusaro submitted a review, later dismissed
Can you update the changelog?

2021-04-22 07:56 UTC, QuiCM approved these changes

2021-04-22 07:56 UTC, merged