Change max buff limit from short to int
Pryaxis/TShock pull request #2300
Opened 2021-05-12 17:48 UTC by moisterrific

trying something pls ignore this for now

2021-05-12 17:50 UTC, bartico6 commented
This is technically possible as player buffs are sent as int32s now, not int16.
I'm nearly confident they were int16s at one point, though.

2021-05-12 17:55 UTC, moisterrific commented
> This is technically possible as player buffs are sent as int32s now, not int16.
> I'm nearly confident they were int16s at one point, though.

I just tested in-game and it doesn't work lol

2021-05-12 18:17 UTC, moisterrific commented
So after extensive trial and error testing, the max possible duration you can set to a buff is exactly `35791393` seconds. The text under the icon says that's approx. 415 days.

![Terraria_2021_05_12_14_15_42_176 (2)](https://user-images.githubusercontent.com/57187883/118024454-b5811280-b32c-11eb-8702-5e6ab6b8eb0c.png)

2021-05-12 21:44 UTC, bartico6 commented
If you want to cap this at maximum, instead of hardcoding the value use the formula derived for it:

`var max_time = (int.MaxValue / 60) - 1`

Also keep default time (the one given if you give a bad time parameter) = 60, don't extend it into 415 days.

Other than that, LGTM

2021-05-13 08:14 UTC, QuiCM requested changes

2021-05-13 08:14 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					time = timeLimit;
Agreed with Quake on this one, keep default time as 60 (approx 1 second)

2021-05-13 09:06 UTC, hakusaro commented
I guess I'm kinda confused. To me it looks like the intent is to set it as long as possible by @moisterrific. I don't think it's bad to let it go for 415 days if the game supports it.

2021-05-13 13:03 UTC, moisterrific commented on TShockAPI/Commands.cs
> +					time = timeLimit;
Yes I've done that in the most recent commit. If the player didn't input any duration, the buff will default to 60 seconds. I wanted to make it easier to get the highest possible time so if you enter something like `-1` for duration it will give you 415 days. Also updated the HelpText to reflect this. 
`/buff 1`
`/buff 1 -1`
`/help buff`

![Terraria_2021_05_13_08_54_53_977](https://user-images.githubusercontent.com/57187883/118128880-7ce34680-b3c9-11eb-9c02-da3e133cb214.png)

Though I would argue it's not a big deal if you accidentally gave yourself a debuff for 415 days since you can just go to the Nurse to remove that or use `/kill`.

2021-05-13 13:08 UTC, moisterrific commented
> I guess I'm kinda confused. To me it looks like the intent is to set it as long as possible by @moisterrific. I don't think it's bad to let it go for 415 days if the game supports it.

yup that's what I intended at first, never understood why it defaulted to 60 sec

2021-05-13 15:55 UTC, bartico6 commented
While talking to existing users I was told this is an existing use situation that they rely on the 60sec default while testing buffs.
Maybe extending to 415d is the way but I'm not sure.

2021-05-13 17:55 UTC, hakusaro commented
I think this calls for...an option or a new command or a switch!

2021-05-14 00:05 UTC, QuiCM submitted a review, later dismissed

2021-05-14 00:06 UTC, QuiCM commented
Given there's no way to obtain 415 days of buff time legitimately in the game (as far as I know), I feel its a little over the top to *by default* provide 415 days of buff time upon using the command without arguments. Especially if its requires the player to die or visit an NPC to remove said buff.

Having a sane default and providing an option for the max time is a fair and reasonable solution in my opinion (and keeps the existing usage the same, with the addition of the max time option).
The `-1` value acts as a switch, so I don't think a new command is necessary.

Happy to merge this as-is, or continue to discuss

2021-05-14 00:10 UTC, hakusaro commented
Yeah my POV and probably @moisterrific’s is that the command implies that you’re turning it on, not applying the default game behavior. I’m more or less ambivalent though I think that supporting both works if that’s what @moisterrific wants

2021-05-14 00:14 UTC, Killia0 commented
I'm not really a contributor to TShock but I second what @QuiCM said, getting the maximum time possible on accident feels like unexpected behavior, and if you need to add a new command or switch that is outside of scope of just allowing the values to be set to higher values. (at that point, if having a buff that lasts forever with less typing is desired why not build in a permabuff command/system to the tshock plugin where you can easily add and clear them)

2021-05-14 00:21 UTC, bartico6 commented
For reference: In my earlier response, @Killia0 is one of the existing users mentioned.

I also personally strongly believe that not specifying a valid time (aka, /buff "glowing" or /buff 15) should give the buff for a fixed short interval, preferably the time a potion of that type would give you - if you do specify the time (especially type -1) the 415d variant should instead be used.

2021-05-14 00:54 UTC, moisterrific commented
> For reference: In my earlier response, @Killia0 is one of the existing users mentioned.
> 
> 
> 
> I also personally strongly believe that not specifying a valid time (aka, /buff "glowing" or /buff 15) should give the buff for a fixed short interval, preferably the time a potion of that type would give you - if you do specify the time (especially type -1) the 415d variant should instead be used.

I like this idea, but what about buffs that are not necessarily time based? Fallback to 60s?

Also do you think it makes more sense to change the max duration option from -1 to just 0?

2021-05-14 00:58 UTC, bartico6 commented
> 
> 
> > For reference: In my earlier response, @Killia0 is one of the existing users mentioned.
> > I also personally strongly believe that not specifying a valid time (aka, /buff "glowing" or /buff 15) should give the buff for a fixed short interval, preferably the time a potion of that type would give you - if you do specify the time (especially type -1) the 415d variant should instead be used.
> 
> I like this idea, but what about buffs that are not necessarily time based? Fallback to 60s?
> 
> Also do you think it makes more sense to change the max duration option from -1 to just 0?

`-1` is commonly known amongst programmers as a "magic value" for `undefined` (and in terms of time periods - intuitive as infinity) - buffing yourself for `0` seconds makes less sense to me than it would to buff myself for `-1` - but that's because of my programming background and familiarity with using -1 as such a value. Whether it makes sense to your average user - I don't know. An alternative time quasi-parameter named "max" or something would be a lot friendlier for sure.

Buffs that aren't time based? You mean.... ones unobtainable with potions, yes? Fall back to a sensible default, 60 would suffice.

**This all is my opinion, pls wait for others' inputs, especially Chris and shank since they're marked in this PR**

2021-05-14 01:33 UTC, hakusaro commented
Yeah I would go with -1 or 0. -1 is probably more intuitive to be infinity.

2021-05-14 17:48 UTC, QuiCM approved these changes

2021-05-20 08:56 UTC, hakusaro approved these changes

2021-05-20 09:40 UTC, merged