Fix Torch God biome torch swap issue
Pryaxis/TShock pull request #2353
Opened 2021-05-27 17:02 UTC by moisterrific

Can confirm this fixes the issue but not sure if it opens any new exploits

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
not yet

2021-05-28 07:07 UTC, hakusaro requested changes
Thanks for your pull-request! Can you change the formatting so that you're indenting both the logical `and` et the arguments to `ConsoleError` so that they're easier to read?

2021-05-28 07:07 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +						args.Player.Name, action, editData, style, selectedItem.placeStyle);
```suggestion
							args.Player.Name, action, editData, style, selectedItem.placeStyle);
```

2021-05-28 07:07 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +					&& (selectedItem.placeStyle != style))
```suggestion
						&& (selectedItem.placeStyle != style))
```

2021-05-28 12:47 UTC, moisterrific commented
> Thanks for your pull-request! Can you change the formatting so that you're indenting both the logical `and` et the arguments to `ConsoleError` so that they're easier to read?

sure thing

2021-05-29 02:54 UTC, hakusaro commented
> sure thing

I actually fixed it for you but your fork isn't writable to us so I can't push it :S

2021-05-29 03:18 UTC, hakusaro approved these changes
![lgtm_trick](https://user-images.githubusercontent.com/532647/120056550-d6668a80-bff1-11eb-96bb-8b82d9c2fc00.gif)

2021-05-29 03:25 UTC, merged