Fix invalid group problems & error reporting on startup
Pryaxis/TShock pull request #2397
Opened 2021-07-13 19:43 UTC by bartico6

Server will no longer start up without the two essential groups (default and guest).
![](https://i.quake.tf/1626205229-29014585.png)

Additionally, players whose groups are removed in the database will no longer be stuck on connecting phase, and are instead disconnected with a descriptive message.
![](https://i.quake.tf/1626205140-48536470.png)

The server now also correctly reports startup errors in the console. The previous call to 'Error' instead of 'ConsoleError' caused the error to appear in the log, but not in the console, leading to a confusing situation for both users and developers where the server would randomly terminate mid-startup.

2021-07-24 23:58 UTC, hakusaro requested changes
I think this is a really good step to helping our support issues. I think, though, I'm a bit unsure if we should just have `Assert` and `Ensure` methods. `Ensure` seems to me like something that would create it if it didn't exist. I would prefer that `Ensure` did that, actually, else it should just be something like `Assert` just like the other method.

Fundamentally, though, I think if a player tries to join and their group is gone, you should also output an exception and tell someone how to resolve the issue, too.

Basically, I would say that this is good, but you'll probably want to convey more to the server operator. The `Ensure` method is more of a subset of `Assert` and they both try to accomplish similar things, so I'd suggest just combining them so that there's always an exception going to a server console. If the login fails because the group doesn't exist, that can be a separate thing.

Also, because this will probably cause someone some heart ache, I would suggest noting in the changelog exactly what will happen if groups are missing in which stages of the connection and startup process.

2021-07-24 23:58 UTC, hakusaro commented on TShockAPI/Utils.cs
> +        {
Can you indent this with tabs?

2021-07-24 23:58 UTC, hakusaro commented on CHANGELOG.md
> +* Fixed missing group problems & error reporting on startup. (@bartico6)
Can you be as specific and descriptive as possible with how you did this?

2021-07-24 23:58 UTC, hakusaro commented on TShockAPI/Utils.cs
> +		public bool AssertGroupValid(TSPlayer player, Group group, bool kick)
Can you move this into the group manager place/thing? We're trying not to add anything else into utils, because it's kinda just the trash dumping ground. I don't want you to just chuck something in, because then it has to live with the other `Dump` methods, which really make this look kinda...redheaded.

2021-07-24 23:58 UTC, hakusaro commented on TShockAPI/TShock.cs
> +				Groups.EnsureCoreGroupsPresent();
Couldn't this happen on the constructor for the GroupManager?

2021-07-24 23:58 UTC, hakusaro commented on TShockAPI/DB/GroupManager.cs
> +            }
Can you indent using tabs here?

2021-07-24 23:58 UTC, hakusaro commented on TShockAPI/DB/GroupManager.cs
> +            {
Can you indent using tabs here?

2021-07-31 14:30 UTC, bartico6 commented
My sincere apologies for the delay, I'll get around to it now.

2021-07-31 14:39 UTC, bartico6 commented
This should be good now, I made the changes you requested & resolved the merge conflict that came up.

2021-08-02 10:41 UTC, QuiCM submitted a review, later dismissed

2021-08-03 05:30 UTC, hakusaro requested changes
Hmm, this still adds a method to TShock.Utils, but you marked my last comment as resolved. So I unresolved it.

I'm not quite sure what the status is if a user joins in a bad state. I guess it sucks but it's better than kicking them?

Why did the submodule change?

2021-08-03 05:30 UTC, hakusaro commented on CHANGELOG.md
> +* The server now correctly disconnects players with missing groups instead of throwing an exception, stalling the connection (@bartico6)
```suggestion
  * The server now correctly disconnects players with missing groups instead of throwing an exception, stalling the connection (@bartico6)
```

2021-08-03 05:30 UTC, hakusaro commented on CHANGELOG.md
> +* The server now rejects login attempts from players who would end up with a missing group. (@bartico6)
```suggestion
  * The server now rejects login attempts from players who would end up with a missing group. (@bartico6)
```

2021-08-03 05:30 UTC, hakusaro commented on TShockAPI/Commands.cs
> +						return;
At this return path, wouldn't the user be left in an inconsistent state since they've been connected but everything else is broken?

2021-08-03 05:41 UTC, bartico6 commented on TShockAPI/Commands.cs
> +						return;
No, this is the login command. If they try to log in into an account that would break their groups this rejects the login attempt. But now I'm doubting my own code lol

2021-08-03 05:42 UTC, bartico6 commented
I merged gendev because of a merge conflict so maybe that's why?
Also forgot to remove the method in utils after moving it to group manager it seems.

2021-08-03 05:50 UTC, hakusaro commented
> I merged gendev because of a merge conflict so maybe that's why?

![photo_2021-08-02 22 50 39](https://user-images.githubusercontent.com/532647/127964671-8b8e2566-519f-4607-ac3b-aeae0a3b51aa.jpeg)

2021-08-07 07:51 UTC, hakusaro commented
@bartico6 you still hacking on this or nah?

2021-08-07 11:33 UTC, bartico6 commented
Oh my, I forgot to update it again. I'll fix it in an hour, sincere apologies :c

2021-08-07 12:01 UTC, bartico6 commented
This time this *really* should be good. Please check :-)

2021-08-08 00:37 UTC, hakusaro requested changes
This is almost ready for merge, but the submodule change will revert TSAPI back by 1 commit to the tree from DeathCradle's fork, not the tree post merge. Can you undo that change? Everything else lgtm!

2021-08-08 10:29 UTC, bartico6 commented
I'm not sure what I'm supposed to do here, I didn't make any changes to TSAPI myself, only did a merge from general-devel... should I do it again? should I forcibly checkout the previous submodule version?

2021-08-08 10:33 UTC, bartico6 commented
This explains what I did. As a sidenote it appears I.. checked out `disable-commands` in the work tree? I guess I was checking something and forgot to undo it, it has been a month. Sorry for the idiotic commits, we might want to squash it maybe?
![obraz](https://user-images.githubusercontent.com/3310937/128629022-b1356101-6c2f-4c57-8d93-9c758963c42e.png)

2021-08-25 04:58 UTC, hakusaro approved these changes
![lgtm_7](https://user-images.githubusercontent.com/532647/130729166-456eb481-c38c-481b-924d-f82662bd852b.gif)

2021-08-25 09:48 UTC, QuiCM approved these changes

2021-08-25 09:52 UTC, merged