Introduce `SoftcoreOnly` config option to allow only softcore characters to connect.
Pryaxis/TShock pull request #2398
Opened 2021-07-14 01:52 UTC by drunderscore

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
yes

2021-07-24 23:41 UTC, hakusaro requested changes
Can you add a description to this PR and move the changelog item to the newest upcoming changes section?

2021-07-25 00:29 UTC, hakusaro submitted a review, later dismissed
![lgtm_4](https://user-images.githubusercontent.com/532647/126884023-70c9b2dd-34a1-45fd-a3ee-d4f9880843be.gif)

2021-08-01 12:15 UTC, bartico6 approved these changes, later dismissed
Sweet and simple, looks good to merge

2021-08-02 10:36 UTC, QuiCM approved these changes

2021-08-02 10:39 UTC, merged