Improved the `/grow` command to reduce code duplication, and allow easy future modification.
Pryaxis/TShock pull request #2400
Opened 2021-07-16 06:10 UTC by drunderscore

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
yes

2021-07-24 23:40 UTC, hakusaro requested changes
I think this improves things, can you further refine the sub-methods that you've implemented and name them in lower camel case since they're embedded inside...a different section?

2021-07-24 23:40 UTC, hakusaro commented on TShockAPI/Commands.cs
> +					bool Prepare(ushort type = 2, bool evil = false)
Can you rename this to something more descriptive of what it does? `Prepare` doesn't really make it clear. Why does it default to type 2? What is evil and why is it a parameter?

2021-07-24 23:40 UTC, hakusaro commented on TShockAPI/Commands.cs
> +						if(!growevilAmb)
Do you mind renaming `growevilAmb` while you're here, since that's really unintuitive?

2021-07-24 23:40 UTC, hakusaro commented on TShockAPI/Commands.cs
> +					bool PerformPermissionCheck()
Can you rename this to something that's more clear? Like rejectUnlessgrowevilAmb?

2021-07-24 23:40 UTC, hakusaro commented on TShockAPI/Commands.cs
> +					bool GrowTree(ushort type, string fancyName, bool evil = false)
Fancy name?

2021-07-24 23:40 UTC, hakusaro commented
Also while I'm here, can you move the changelog item into the new upcoming changes section, and add a description to this PR?

2021-12-07 08:15 UTC, drunderscore commented on TShockAPI/Commands.cs
> +					bool PerformPermissionCheck()
I've renamed this to `rejectCannotGrowEvil`

2021-12-07 08:15 UTC, drunderscore commented on TShockAPI/Commands.cs
> +					bool Prepare(ushort type = 2, bool evil = false)
I've renamed this method to `prepareAreaForGrow`

2021-12-07 08:17 UTC, drunderscore commented
I've implemented all suggested changes and rebased this PR -- I left it alone for a bit too long.

2021-12-08 04:55 UTC, hakusaro submitted a review, later dismissed
![lgtm_7](https://user-images.githubusercontent.com/532647/145150471-c118076f-0990-4ecc-89fa-0ae3efc1615d.gif)

2022-02-22 08:15 UTC, QuiCM approved these changes, later dismissed

2022-02-22 08:21 UTC, QuiCM approved these changes

2022-02-22 08:27 UTC, hakusaro approved these changes

2022-02-22 08:28 UTC, hakusaro commented
![145150471-c118076f-0990-4ecc-89fa-0ae3efc1615d](https://user-images.githubusercontent.com/532647/155092477-879bf4ef-b0f7-49d2-9ead-91279f812aff.gif)

2022-02-22 08:44 UTC, merged