Typo fixes on comments/strings
Pryaxis/TShock pull request #2401
Opened 2021-07-16 18:54 UTC by Killia0

My first PR contribution to TShock is spellcheck huh, frankly I don't know why but hey I could spare the time for this and caught some stuff.

> ?????? HAVE YOU UPDATED THE CHANGELOG? ??????
No. this is just typo fixes with a spellchecker and deserves no credit.

2021-07-24 23:28 UTC, hakusaro submitted a review, later dismissed
Thank you so much!

> No. this is just typo fixes with a spellchecker and deserves no credit.

This is a lie! Please, in the future, update the changelog.

2021-07-25 00:04 UTC, hakusaro requested changes
Minor issue with the changelog's timespace contunity, can you adjust?

2021-07-25 00:04 UTC, hakusaro commented on CHANGELOG.md
> +* Fix some typos that have been in the repository for over a lustrum. (@Killia0)
Can you add this chronologically after the commit from Stealownz?

2021-07-25 00:15 UTC, Killia0 commented on CHANGELOG.md
> +* Fix some typos that have been in the repository for over a lustrum. (@Killia0)
You mean, before it? because currently it is after

2021-07-25 00:17 UTC, hakusaro commented on CHANGELOG.md
> +* Fix some typos that have been in the repository for over a lustrum. (@Killia0)
@Killia0 no, the changelog is:
1. first thing that changed
2. second thing that changed
3. third thing that changed

not the reverse, sorry.

2021-07-25 00:21 UTC, Killia0 commented on CHANGELOG.md
> +* Fix some typos that have been in the repository for over a lustrum. (@Killia0)
Huh, I see. I notice now that I also removed the `## TShock 4.5.5` on accident, Fixed now.

2021-07-25 00:23 UTC, hakusaro approved these changes
![lgtm_7](https://user-images.githubusercontent.com/532647/126883934-5270d568-53bb-4b67-8101-83556b448180.gif)

2021-07-25 00:24 UTC, merged