Add Lunatic Cultist summonboss permission check
Pryaxis/TShock pull request #2402
Opened 2021-07-16 19:03 UTC by moisterrific

I was going to add this into the prev empress summon perm check but @QuiCM already merged that lol

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
yes

2021-07-24 23:27 UTC, hakusaro requested changes
Can you make this a separate changelog item and move it into the new upcoming changes section?

2021-07-25 00:20 UTC, hakusaro approved these changes, later dismissed
![lgtm_trick](https://user-images.githubusercontent.com/532647/126883903-1c32651e-68ae-4409-a1bb-f8947c052bab.gif)

2021-08-02 09:35 UTC, QuiCM approved these changes, later dismissed

2021-08-02 09:39 UTC, QuiCM approved these changes

2021-08-02 10:34 UTC, merged