various improvements to commands
Pryaxis/TShock pull request #2404
Opened 2021-07-17 00:44 UTC by moisterrific

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
no bc there's some kinda file conflict i think 🤦🏻‍♀️

2021-07-21 09:04 UTC, QuiCM requested changes

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				HelpText = "Heals the HP of yourself or another player."
```suggestion
				HelpText = "Restores the HP of yourself or another player."
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					  "martians"
Spacing issue? Github doesn't want to render whitespace, but I assume this is tabs->spaces

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					TSPlayer.All.SendInfoMessage($"{args.Player.Name} cleared all players from today's angler quest completion list.");
```suggestion
				else
				{
					TSPlayer.All.SendInfoMessage($"{args.Player.Name} cleared all players from today's angler quest completion list.");
				}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				TSPlayer.All.SendInfoMessage($"{args.Player.Name} set the world mode {_worldModes.Keys.ElementAt(mode)}");
```suggestion
			else
			{
				TSPlayer.All.SendInfoMessage($"{args.Player.Name} set the world mode {_worldModes.Keys.ElementAt(mode)}");
			}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					TSPlayer.All.SendInfoMessage($"{args.Player.Name} turned off Hardmode.");
```suggestion
				if (args.Silent)
				{
					args.Player.SendSuccessMessage("Hardmode is now off.");
				}
				else
				{
					TSPlayer.All.SendInfoMessage($"{args.Player.Name} turned off Hardmode.");
				}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					TSPlayer.All.SendInfoMessage($"{args.Player.Name} turned on Hardmode.");
```suggestion
				if (args.Silent)
				{
					args.Player.SendSuccessMessage("Hardmode is now on.");
				}
				else
				{
					TSPlayer.All.SendInfoMessage($"{args.Player.Name} turned on Hardmode.");
				}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendErrorMessage($"Invalid syntax! Proper syntax: {Specifier}spawnmob <mob type> [amount]", Specifier);
```suggestion
				args.Player.SendErrorMessage($"Invalid syntax! Proper syntax: {Specifier}spawnmob <mob type> [amount]");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendErrorMessage($"Invalid syntax! Proper syntax: {Specifier}spawnmob <mob type> [amount]", Specifier);
```suggestion
				args.Player.SendErrorMessage($"Invalid syntax! Proper syntax: {Specifier}spawnmob <mob type> [amount]");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendErrorMessage($"Invalid syntax! Proper syntax: {Specifier}spawnboss <boss name> [amount]", Specifier);
```suggestion
				args.Player.SendErrorMessage($"Invalid syntax! Proper syntax: {Specifier}spawnboss <boss name> [amount]");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +						args.Player.SendErrorMessage($"{target.Name} has disabled players from teleporting to {(target.TPlayer.Male ? "him" : "her")}");
```suggestion
						args.Player.SendErrorMessage($"{target.Name} has disabled players from teleporting to them.");
```

Gender neutrality is probably better here

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +								TShock.Players[i].SendSuccessMessage($"{args.Player.Name} has teleported you to {(args.Player.TPlayer.Male ? "his" : "her")} location.");
```suggestion
								TShock.Players[i].SendSuccessMessage($"{args.Player.Name} has teleported you to their location.");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					plr.SendInfoMessage($"{args.Player.Name} has teleported you to {(args.Player.TPlayer.Male ? "his" : "her")} location.");
```suggestion
					plr.SendInfoMessage($"{args.Player.Name} has teleported you to their location.");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +			args.Player.SendSuccessMessage($"Teleported to {x}, {y}!", x, y);
```suggestion
			args.Player.SendSuccessMessage($"Teleported to {x}, {y}!");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					args.Player.SendInfoMessage($"Examples: {Specifier}warp add foobar, {Specifier}warp hide foobar true, {Specifier}warp foobar");
Suggestion:
Add colours here? Same highlighting as ban command

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				TSPlayer.All.SendInfoMessage($"{args.Player.Name} has set spawn at {(args.Player.TPlayer.Male ? "his" : "her")} location.");
```suggestion
			if (args.Silent)
			{
				args.Player.SendSuccessMessage("Spawn has now been set at your location.");
			}
			else
			{
				TSPlayer.All.SendInfoMessage($"{args.Player.Name} has set spawn at their location.");
			}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				TSPlayer.All.SendInfoMessage($"{args.Player.Name} has set the dungeon at {(args.Player.TPlayer.Male ? "his" : "her")} location.");
```suggestion
			if (args.Silent)
			{
				args.Player.SendSuccessMessage("The dungeon's position has now been set at your location.");
			}
			else
			{
				TSPlayer.All.SendInfoMessage($"{args.Player.Name} has set the dungeon at their location.");
			}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendInfoMessage($"The current time is {(int)Math.Floor(time)}:{(int)Math.Floor((time % 1.0) * 60.0):D2}.");
Extract this into variables for clarity

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +						TSPlayer.All.SendInfoMessage($"{args.Player.Name} set the time to midnight (12:00 AM / 00:00).");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				TSPlayer.All.SendInfoMessage($"{args.Player.Name} changed the wind speed to {speed}.");
```suggestion
			if (args.Silent)
			{
				args.Player.SendSuccessMessage($"You changed the wind speed to {speed}");
			}
			else
			{
				TSPlayer.All.SendInfoMessage($"{args.Player.Name} changed the wind speed to {speed}.");
			}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				TSPlayer.All.SendSuccessMessage($"{args.Player.Name} has {(TShock.Config.Settings.SpawnProtection ? "en" : "dis")}abled spawn protection.");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +						players.Add(String.Format($"{ply.Name} (Index: {ply.Index}{(ply.Account != null ? ", Account ID: " + ply.Account.ID : "")})"));
```suggestion
						players.Add($"{ply.Name} (Index: {ply.Index}{(ply.Account != null ? ", Account ID: " + ply.Account.ID : "")})");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					TSPlayer.All.SendInfoMessage($"{args.Player.Name} has unmuted {plr.Name}.");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					TSPlayer.All.SendInfoMessage($"{args.Player.Name} has muted {plr.Name} for {reason}.");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				plr.SendMessage(String.Format($"<From {args.Player.Name}> {msg}"), Color.MediumPurple);
```suggestion
				plr.SendMessage($"<From {args.Player.Name}> {msg}", Color.MediumPurple);
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendMessage(String.Format($"<To {plr.Name}> {msg}"), Color.MediumPurple);
```suggestion
				args.Player.SendMessage($"<To {plr.Name}> {msg}", Color.MediumPurple);
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendMessage(String.Format($"<To {args.Player.LastWhisper.Name}> {msg}"), Color.MediumPurple);
```suggestion
				args.Player.LastWhisper.SendMessage($"<From {args.Player.Name}> {msg}", Color.MediumPurple);
				args.Player.SendMessage($"<To {args.Player.LastWhisper.Name}> {msg}", Color.MediumPurple);
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendErrorMessage($"{players} is not a valid player!");
```suggestion
				args.Player.SendErrorMessage($"{args.Parameters[0]} is not a valid player!");
```
`players` will be an empty list here.

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					args.Player.SendErrorMessage($"You cannot rocket {ply.Name} because {(ply.TPlayer.Male ? "he" : "she")} is not logged in.");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					args.Player.SendErrorMessage($"You cannot rocket {ply.Name} because {(ply.TPlayer.Male ? "he" : "she")} is not logged in.");
```suggestion
					if (args.Silent)
						args.Player.SendSuccessMessage($"You rocketed {ply.Name}.");
					else
						// Should this be TSPlayer.All or plr?
						TSPlayer.All.SendInfoMessage($"{args.Player.Name} has launched {ply.Name} into orbit.");
				}
				else if (!Main.ServerSideCharacter)
					args.Player.SendErrorMessage("Server Side Character must be enabled to use this command!");
				else if (!ply.IsLoggedIn)
					args.Player.SendErrorMessage($"You cannot rocket {ply.Name} because they are not logged in.");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendErrorMessage($"{players} is not a valid player!");
```suggestion
				args.Player.SendErrorMessage($"{args.Parameters[0]} is not a valid player!");
```
`players` will be an empty list here

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +						type = ProjectileID.RocketFireworkYellow;
Replace with a switch block

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					TSPlayer.All.SendInfoMessage($"{args.Player.Name} launched firework on {ply.Name}");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +			args.Player.SendTileSquare((int)args.Player.TileX - localSize, (int)args.Player.TileY - localSize, localSize * 2);
Add a comment for this to explain the math

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +							TSPlayer.All.SendInfoMessage($"{args.Player.Name} deleted {cleared} item{(cleared > 1 ? "s" : "")} within a radius of {radius}");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +							TSPlayer.All.SendInfoMessage($"{args.Player.Name} deleted {cleared} NPC{(cleared > 1 ? "s" : "")} within a radius of {radius}");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +							TSPlayer.All.SendInfoMessage($"{args.Player.Name} deleted {cleared} projectile{(cleared > 1 ? "s" : "")} within a radius of {radius}");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					plr.SendErrorMessage($"{args.Player.Name} just killed you!");
```suggestion
				if (!args.Silent)
				{
					plr.SendErrorMessage($"{args.Player.Name} just killed you!");
				}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					args.Player.SendErrorMessage($"{npcs} is not a valid NPC type!");
```suggestion
					args.Player.SendErrorMessage($"{args.Parameters[0]} is not a valid NPC type!");
```
`npcs` is an empty list here

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				TSPlayer.All.SendInfoMessage($"{args.Player.Name} butchered {kills} NPC{(kills > 1 ? "s" : "")}.");
Add braces on if/else for consistency

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					args.Player.SendErrorMessage("Invalid NPC type!");
```suggestion
					args.Player.SendErrorMessage($"{args.Parameters[0]} is not a valid NPC type!");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +					TSPlayer.All.SendInfoMessage($"{args.Player.Name} renamed the {npcType} to {args.Parameters[1]}.");
```suggestion
				else
				{
					TSPlayer.All.SendInfoMessage($"{args.Player.Name} renamed the {npcType} to {args.Parameters[1]}.");
				}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +									plr.SendSuccessMessage($"{args.Player.Name} gave you {itemAmount} {item.Name}{(itemAmount > 1 ? "s" : "")}.");
```suggestion
								if (!args.Silent)
								{
									plr.SendSuccessMessage($"{args.Player.Name} gave you {itemAmount} {item.Name}{(itemAmount > 1 ? "s" : "")}.");
								}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +							args.Player.SendSuccessMessage($"You just healed yourself for {amount} HP!");
```suggestion
							args.Player.SendSuccessMessage($"You have healed yourself for {amount} HP!");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +			if (args.Parameters.Count == 1)
```suggestion
			else if (args.Parameters.Count == 1)
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +							args.Player.SendSuccessMessage($"You just healed yourself for {amount} HP!");
```suggestion
							args.Player.SendSuccessMessage($"You have healed yourself for {amount} HP!");
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +			if (args.Parameters.Count == 2)
```suggestion
			else if (args.Parameters.Count == 2)
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				args.Player.SendSuccessMessage($"{playerToGod.Name} is {(playerToGod.GodMode ? "now" : "no longer")} in god mode.");
```suggestion
			{
				args.Player.SendSuccessMessage($"{playerToGod.Name} is {(playerToGod.GodMode ? "now" : "no longer")} in god mode.");
			}
```

2021-07-21 09:04 UTC, QuiCM commented on TShockAPI/Commands.cs
> +				playerToGod.SendSuccessMessage($"You are {(args.Player.GodMode ? "now" : "no longer")} in god mode.");
```suggestion
			{
				playerToGod.SendSuccessMessage($"You are {(args.Player.GodMode ? "now" : "no longer")} in god mode.");
			}
```

2021-07-24 23:17 UTC, hakusaro commented on TShockAPI/Commands.cs
> +					  "martians"
This is indented 5 tabs and 2 spaces. The previous items in this list are indented by 3 tabs.

2021-07-24 23:18 UTC, hakusaro requested changes
Can you add a description to this pull request so that we know what changed?

2021-08-02 15:40 UTC, closed without merging