Add notify msg for online player group change
Pryaxis/TShock pull request #2405
Opened 2021-07-17 18:49 UTC by moisterrific

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
yes

2021-07-21 07:26 UTC, QuiCM requested changes

2021-07-21 07:26 UTC, QuiCM commented on TShockAPI/Commands.cs
> +						players[0].SendSuccessMessage($"{args.Player.Name} has changed your group to {args.Parameters[2]}");
```suggestion
					//send message to player with matching account name
					var player = TShock.Players.FirstOrDefault(p => p != null && p.Account?.Name == account.Name)
					if (player != null && !args.Silent)
						player.SendSuccessMessage($"{args.Player.Name} has changed your group to {args.Parameters[2]}");
```

2021-07-21 07:26 UTC, QuiCM commented on TShockAPI/Commands.cs
> +						players[0].SendSuccessMessage($"{args.Player.Name} has changed your group to {args.Parameters[2]}");
Pleaase note this suggestion was written by hand & untested - will need to be sanity checked

2021-07-22 02:32 UTC, moisterrific commented on TShockAPI/Commands.cs
> +						players[0].SendSuccessMessage($"{args.Player.Name} has changed your group to {args.Parameters[2]}");
I can test it and let u know

2021-07-24 21:18 UTC, moisterrific reviewed
?

2021-07-24 21:18 UTC, moisterrific commented on TShockAPI/Commands.cs
> +						players[0].SendSuccessMessage($"{args.Player.Name} has changed your group to {args.Parameters[2]}");
tested it and it works, just missing a `;`

2021-07-24 23:16 UTC, hakusaro requested changes
This is pretty good but why does the PR not have any description of what changed?

2021-07-24 23:31 UTC, moisterrific commented
> 
> 
> This is pretty good but why does the PR not have any description of what changed?

fixed

2021-07-25 00:15 UTC, hakusaro submitted a review, later dismissed

2021-08-02 09:34 UTC, QuiCM approved these changes, later dismissed

2021-08-02 15:15 UTC, QuiCM approved these changes

2021-08-02 15:15 UTC, merged