Improve login error messages and post-register process
Pryaxis/TShock pull request #2406
Opened 2021-07-20 00:17 UTC by moisterrific

* Now `/login` related error messages tell players ONLY the relevant info they need to know on how to sign in to their account
* Added new info messages fired after successful `/register` process, telling players how they can `/login`

?????? HAVE YOU UPDATED THE CHANGELOG? ??????
maybe

2021-07-21 07:18 UTC, QuiCM approved these changes, later dismissed

2021-07-22 02:33 UTC, hakusaro commented
I will check after headache

2021-07-24 23:14 UTC, hakusaro requested changes
This is mostly good, but I think you can make it simpler by only checking the first condition in your if statements once, and then providing feedback after.

2021-07-24 23:14 UTC, hakusaro commented on TShockAPI/Commands.cs
> +				if (TShock.Config.Settings.DisableUUIDLogin && !TShock.Config.Settings.AllowLoginAnyUsername)
Can you combine this into one if statement and another if statement instead of an if/else that has the same first part of the conditonal?

e.g.,

```csharp
if (the cow is raining) {
    if (the cow has jam) {
        // stuff
     } else {
       // other stuff
   }
}  else {
      // the cow is not raining
}
```

2021-07-24 23:14 UTC, hakusaro commented on TShockAPI/Commands.cs
> +					if (TShock.Config.Settings.DisableUUIDLogin && !TShock.Config.Settings.AllowLoginAnyUsername)
Can you change this exactly the way I suggested above for the other one?

2021-07-24 23:14 UTC, hakusaro commented on CHANGELOG.md
> +* Improved `/login` related error messages and made the `/register` process more friendly for players new to TShock. (@moisterrific)
```suggestion
* Changed `/login` and `/register` provide login help depending on if UUID login is enabled or disabled, and whether or not a player can login via any username or not. (@moisterrific)
```

2021-07-25 00:40 UTC, moisterrific commented
How's this?

2021-07-25 00:54 UTC, hakusaro requested changes
Okay, sorry, I need to clarify. Maybe these need to be independent checks? if DisableUUIDLogin is false, but AllowLoginAnyUsername is true, you can still use the commands that aren't getting help in this context.

2021-07-25 02:54 UTC, moisterrific commented
Third time's the charm?

2021-07-25 18:50 UTC, hakusaro approved these changes, later dismissed
![lgtm_1](https://user-images.githubusercontent.com/532647/126910042-67d06895-7c12-4ba5-ac2d-00952a00c656.gif)


lgtm, but there's a minor suggestion if you want to take it (up to you)!

2021-07-25 18:50 UTC, hakusaro commented on TShockAPI/Commands.cs
> +						args.Player.SendMessage($"Type {Specifier}login to sign in to your account.", Color.White);
```suggestion
						args.Player.SendMessage($"Type {Specifier}login to sign in to your account using your UUID.", Color.White);
```

2021-07-25 20:37 UTC, hakusaro submitted a review, later dismissed

2021-08-02 09:32 UTC, QuiCM approved these changes

2021-08-02 09:32 UTC, merged