Fix return for sundail
Pryaxis/TShock pull request #2437
Opened 2021-08-23 21:01 UTC by Rozen4334

2021-08-24 13:51 UTC, QuiCM submitted a review, later dismissed
I think this looks ok but GitHub mobile melted my brain a little

2021-08-24 13:55 UTC, QuiCM commented
Logic flow could be adjusted with new positioning of the returns, but purely semantic. Happy for this to be merged if no other queries/complaints

2021-08-25 04:56 UTC, hakusaro requested changes
Only reading this PR alone, there is no description and the changelog doesn't elaborate on what the sundial problem is. I do apologize but without this PR being self-descriptive, particularly the changelog (which we have been skewered over in the past), it is difficult for me to approve this.

To remedy the situation, please update the changelog and pull-request description such that you've:

1. Described the sundial problem.
2. Described what you've changed to fix the sundial problem.

Please note that the changelog is read by both developers and normal people. Unless people are already familiar with the sundial problem, it is extremely difficult to discern how this rectifies the sundial problem.

Thank you so much for your pull request! I hope we can merge it soon.

2021-08-25 04:56 UTC, hakusaro commented on CHANGELOG.md
> +* Changed return in ` HandleSpecial ` (GetDataHandlers) to fix Sundial problem. (@Rozen4334)
What is the sundial problem? Please elaborate more on the sundial problem in this changelog entry.

2021-08-25 10:44 UTC, Rozen4334 commented on CHANGELOG.md
> +* Changed return in ` HandleSpecial ` (GetDataHandlers) to fix Sundial problem. (@Rozen4334)
Hoping I have clarified enough in latest commit.

2021-08-25 11:03 UTC, QuiCM commented on CHANGELOG.md
> +* Changed return result in ` HandleSpecial ` to fix problem where using sundial would be ignored and return true even if succesfully passing checks. (@Rozen4334)
May I suggest
```suggestion
* Fixed a bug that caused sundials to be ignored all the time, instead of only when the player has no permission or time is frozen. (@Rozen4334)
```

2021-08-25 11:11 UTC, Rozen4334 commented on CHANGELOG.md
> +* Changed return result in ` HandleSpecial ` to fix problem where using sundial would be ignored and return true even if succesfully passing checks. (@Rozen4334)
>:D, done

2021-08-25 11:19 UTC, QuiCM approved these changes

2021-08-27 04:50 UTC, hakusaro approved these changes
![lgtm_8](https://user-images.githubusercontent.com/532647/131073479-b99e8a3d-bee1-4e95-bd82-94a96877f394.gif)

2021-08-27 05:16 UTC, merged