Fix player buffs applied to other players through `PlayerAddBuff` packet
Pryaxis/TShock pull request #2453
Opened 2021-09-20 20:08 UTC by drunderscore

Fixed `HandlePlayerAddBuff` data handler always being marked as `Handled`, and therefore never allowing the `PlayerAddBuff` to be sent to anyone.

Fixed `OnPlayerBuff` logic inside of Bouncer when checking `WhitelistBuffMaxTime` to determine if a buff being applied longer than allowed. This also marks the handler as `Handled` if the check fails, and resyncs the buffs with the `PlayerAddBuff` packet to the sender. (@drunderscore)

2021-09-20 20:10 UTC, drunderscore commented
The original bug is that when shooting another player with a Cursed Arrow (to apply Cursed Inferno), the check against `WhitelistBuffMaxTime` was using `<=` instead of `>`, which prevented the buff from being applied -- but never actually did because it was marked as **not** handled. Only a second bug within the `HandlePlayerAddBuff` data handler allowed this bug to continue.

Ichor Arrows (to apply Ichor) will fail simply because of the second bug.

2021-09-21 09:39 UTC, bartico6 requested changes
This is a dangerous change. 
The current buff system says "drop all buffs *UNLESS* whitelisted", whereas your system says "allow all buffs *UNLESS* blacklisted".
The better choice would be to determine the parameters of buffs you can apply in vanilla and add them to the whitelist with the correct times, since that was the goal of this rubberband check in the first place. Doing it the way you just did could reopen the doors for old exploits that this currently stops.

2021-09-21 14:33 UTC, drunderscore commented
@bartico6 Yeah I see what you mean, definitely a good idea to only allow buffs that happen in vanilla to others (which should be a short list regardless)

I'll go through and update `WhitelistBuffMaxTime` with all buffs and their max time, and remove the `> 0` check.

2021-09-21 14:49 UTC, bartico6 commented
Just commit a fix with the buffs you're currently seeing problems with.

2022-03-28 00:13 UTC, hakusaro commented
@bartico6 fyi, this was updated, can you check again?

2022-04-07 03:01 UTC, drunderscore commented
Rebased, whitelisted more buffs, and added `CanOnlyBeAppliedToSender`, to indicate that the sender may only apply this buff to themself. This is used by `BuffIDs.Campfire` (aka Cozy Fire), `BuffID.WaterCandle`, and some others.

2022-04-07 03:54 UTC, hakusaro commented
@drunderscore still has merge conflicts on GitHub on web, can you fix with a rebase so that it runs CI?

2022-04-07 04:01 UTC, drunderscore commented
@hakusaro Fixed! Sorry about that, I actually didn't rebase even though I thought I did...

2022-04-07 09:10 UTC, QuiCM submitted a review, later dismissed
This looks reasonable to me. Would appreciate if @bartico6 would re-review as well

2022-04-27 06:33 UTC, Arthri requested changes

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +		    }
The indentation switched to spaces here

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			if (time > buffLimit.MaxTicks)
I'm not sure what it could be used for, but the time could be negative and it would pass this check

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +		public static BuffLimit[] AddPlayerBuffWhitelist;
I think this should be in Bouncer, it feels a bit out of place in GetDataHandlers

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +			// How many ticks at the maximum a player can apply this to another player for.
I think this would be better as an XML summary/comment, the one with triple slash

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +			// Can this buff be added without the receiver being hostile (PvP)
I think this would be better as an XML summary/comment

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +			// Can this buff only be applied to the sender?
I think this would be better as an XML summary/comment

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 10
Poisoned can be inflicted for up to 60 seconds by Poison Dart(according to the wiki)

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 7 * 60
Minor but, the format is inconsistent here, it's 60 * x everywhere else

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 20
I believe the max is 19, from Flask of Ichor's effect

2022-04-27 06:33 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 8
The max is 14(from Frost Armor) according to the wiki

2022-04-27 22:50 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 10
This does not apply to PvP in practice

2022-04-27 22:52 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 10
I lied -- it does apply to PvP, will change it.

2022-04-27 23:09 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 20
Congratulations, you've discovered a vanilla desync bug -- see https://github.com/Pryaxis/Terraria/issues/9... I will leave it for the future.

2022-04-27 23:16 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 8
Another vanilla desync bug, the server is never informed of this buff... I might make one issue to list all of these over on [Pryaxis/Terraria](https://github.com/Pryaxis/Terraria)... I'll talk about it in Discord

2022-04-28 08:46 UTC, Arthri commented on TShockAPI/GetDataHandlers.cs
> +				MaxTicks = 60 * 20
Ah I see, in that case the max would be 14 from Ichor Dart. I don't remember stuff that inflicts up to 20s ichor

2022-04-28 08:46 UTC, Arthri commented
https://github.com/Pryaxis/TShock/compare/c93cc7bb09d34c19fc908ca201061f5b9fc52f7d..b2214685ca3d49ea009112cb97a1d21e9cf9bd66

2022-05-29 01:39 UTC, drunderscore commented
Added buff limits for `MonsterBanner`, `HeartLamp`, `PeaceCandle`, `StarInBottle`, `CatBast`

2022-05-29 06:42 UTC, Arthri commented
https://github.com/Pryaxis/TShock/compare/b2214685ca3d49ea009112cb97a1d21e9cf9bd66..f53367399fd1baa7aad55ca77f827fa3b2e2f8f6

2022-10-06 04:05 UTC, hakusaro commented
Anyone know the status on this?

2022-10-06 12:26 UTC, drunderscore commented
The Venom buff in `Main.pvpBuff` change will be removed, as it has been corrected by Re-Logic in 1.4.4. All of the existing buff limits will be checked to ensure they are still correct.

There are certainly still some missing buff limits, but I think it would be beneficial to review and merge this, as we would only gain more features.

I'll take another look at this today, and hopefully persuade some others to review.

2022-10-06 15:59 UTC, drunderscore commented
I've rebased this, and the only thing I've removed is the `Main.pvpBuff[BuffID.Venom] = true` patch as described earlier.

@hakusaro or @Arthri if you are able to review, I'd appreciate it -- I believe this to be ready to merge, other missing buff limits can be added in due time.

2022-10-08 17:12 UTC, drunderscore commented
Changed buff limits for Solar Armor (`SolarShield1`, `SolarShield2`, `SolarShield3`), to allow them to be applied by non-senders. Added limits for Hellfire (`OnFire3`), Hearty Meal, and Frostbite (`Frostburn2`).

2022-10-08 17:13 UTC, hakusaro approved these changes

2022-10-15 06:49 UTC, merged