Initial OTAPI3 port
Pryaxis/TShock pull request #2509
Opened 2021-11-23 11:14 UTC by DeathCradle

DO NOT MERGE YET. This is a draft, and SQLite is not yet working and hence why I would like to create a discussion around this.

This PR upgrades TShock to OTAPI3 and .NET5 (6 later on). This is a major/breaking upgrade.

- No testing has occurred at all and once merged into the otapi3 branch it should have full end-end testing. 
- It must not go to general-devel until the entire team is satisfied, and TSAPI would need to do this first as well.
- Packages have updated, need to ensure thy work e.g MySql (havent had a chance to set this up)
- AssemblyInfo.cs was replaced to the .csproj, as it is now shared between the assembly info and nuget package info from there.
- **Currently Mono.Data.Sqlite is used and the sqlite3.dll needs updating to x64, or we need to switch to System.Data.Sqlite which i can confirm already works with a assembly resolver, or Microsoft.Data.Sqlite**

What preference does the team have for the sqlite library on net5 onward? This is my main blocking question at this point.

2021-11-23 16:41 UTC, hakusaro commented
> What preference does the team have for the sqlite library on net5 onward? This is my main blocking question at this point.

I would say`System.Data.Sqlite`.

2021-11-24 01:38 UTC, hakusaro requested changes
I have a couple minor suggestions and a couple questions, other than that this looks okay code-wise.

The only other thing that I kind of want to require is that CI works, because we do rely on CI for basically everything. The current CI outputs are directly used for releases and package everything in the exact correct way it needs to be to ship a release out. Specifically, you can just drag and drop everything from a release onto an existing server to upgrade, which means that every output is packaged correctly in terms of location in `ServerPlugins` or not, and vice versa.

The complication with .net5 is that we need to start shipping assemblies for macOS, Linux, and Windows I guess. Like I already commented, I think the biggest thing is that when we package these for release, we need to make sure that there isn't a billion DLLs in the release folder people download if at all possible. Can we just move everything into a `System` or something folder?

Honestly, we probably need outputs for:
* x64 win
* x64 macOS
* x64 linux
* arm64e macOS
* arm64 linux

I'm not sure if you want to address this toolchain stuff in this PR, or just merge it and then work on subsequent work to get other things done.

**I have not tested this locally yet, but I will do so, soon.**

2021-11-24 01:38 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <Company>Re-Logic, Pryaxis &amp; TShock Contributors</Company>
```suggestion
    <Company>Pryaxis &amp; TShock Contributors</Company>
```

I think we can drop RL from this because we aren't packing their stuff here anymore. I think this copyright was vestigial from back in the "we are shipping their source code with TShock" days.

2021-11-24 01:38 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <Copyright>Copyright © Re-Logic, Pryaxis &amp; TShock Contributors 2011-2021</Copyright>
```suggestion
    <Copyright>Copyright © Pryaxis &amp; TShock Contributors 2011-2021</Copyright>
```

2021-11-24 01:38 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <Content Include="$(OutputPath)\TerrariaServerAPI.dll" IncludeInPackage="true" Pack="true" PackagePath="lib\$(TargetFramework)" />
Should I be asking why we're including TSAPI in the package?

2021-11-24 01:38 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <Copy SourceFiles="$(OutputPath)\System.Data.SQLite.dll" DestinationFolder="$(SolutionDir)\TerrariaServerAPI\TerrariaServerAPI\bin\$(ConfigurationName)\net5.0\ServerPlugins" SkipUnchangedFiles="f
Is there any way to keep non-plugins from the `ServerPlugins` folder? One of my biggest pet peeves with netcore/dotnet 5 is that the build outputs are extremely messy. For the purposes of simplicity, I think I'd prefer if we could throw these dlls somewhere that aren't `ServerPlugins` or the root directory, but if we can't it's fine.

2021-11-24 01:40 UTC, DeathCradle commented on TShockAPI/TShockAPI.csproj
> +    <Content Include="$(OutputPath)\TerrariaServerAPI.dll" IncludeInPackage="true" Pack="true" PackagePath="lib\$(TargetFramework)" />
plugin refs/hooks, since tsapi has no nuget package. though, now is the time if you want to do that...

2021-11-24 01:41 UTC, DeathCradle commented on TShockAPI/TShockAPI.csproj
> +    <Company>Re-Logic, Pryaxis &amp; TShock Contributors</Company>
that one is up to you, so sure? this was just moved from AssemblyInfo.cs

2021-11-24 01:44 UTC, DeathCradle commented on TShockAPI/TShockAPI.csproj
> +    <Copy SourceFiles="$(OutputPath)\System.Data.SQLite.dll" DestinationFolder="$(SolutionDir)\TerrariaServerAPI\TerrariaServerAPI\bin\$(ConfigurationName)\net5.0\ServerPlugins" SkipUnchangedFiles="f
potentially, would need to investigate. e.g. runtimes in debug mode contain the native deps, and we can control the resolution via code.

2021-11-24 01:46 UTC, DeathCradle commented on TShockAPI/TShockAPI.csproj
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
this is why there is a bunch of assemblies. only currently needed for debugging automation (ie copying deps to tsapi so it actually runs).
however, im sure we can streamline this process, and we might need to work out our deployment strategy...which im unsure the best course of action yet. (@tylerjwatson is the legend on this stuff i would assume but he's hella busy)

2021-11-24 02:54 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <Content Include="$(OutputPath)\TerrariaServerAPI.dll" IncludeInPackage="true" Pack="true" PackagePath="lib\$(TargetFramework)" />
@DeathCradle I mean, I think we should just start publishing these as nuget packages but I was unsure if we should move forward with merging this before that

2021-11-24 02:54 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <Company>Re-Logic, Pryaxis &amp; TShock Contributors</Company>
@DeathCradle it's your branch :P

2021-11-24 02:59 UTC, hakusaro commented
I think I would articulate that:

1. In order for me to approve merging it, I need to be able to build locally and test on macOS 12.0.1 (21A559) (arm64e on Rosetta), and currently, I can't do that, and I'm not quite sure why. I just kind of yolo'd this build process, though. If you have better insight on how to build, please let me know.
2. We don't have to get everything right on the merge to `otapi3` given that `general-devel` is the main branch. However, in order to merge to general-devel, most of the issues that I outlined above need to be fixed/rectified. For example, I can work on CI/tooling, or you can, but I don't want to consider that a blocker for a branch on TShock. We can easily just merge the current branch and assemble CI/releases in bits and bobs until we're happy to merge to general-devel.

The timeline of events would look something like this:
1. Merge to otapi3.
2. Get CI working.
3. Publish pre-release builds for people to test with on test servers and test plugins against.
4. Merge to general-devel, so that mainline CI starts occurring.
5. Prepare documentation on what to do/how to do it for things.
6. Publish a freaking docker file or otherwise update Ryshe's docker file so that docker users aren't left out in the cold.
7. Update the readme.
8. Release the stuff.

Currently, 1 is where we're at but we could compress 2 into 1. It just depends on how much work you want to do.

2021-11-24 02:59 UTC, hakusaro commented
Optional steps:
1. Get cute anime girl mascot for tshock (tbd)
2. Figure out how to get plugin developers to update (tbd)

2021-11-24 02:59 UTC, DeathCradle commented on TShockAPI/TShockAPI.csproj
> +    <Content Include="$(OutputPath)\TerrariaServerAPI.dll" IncludeInPackage="true" Pack="true" PackagePath="lib\$(TargetFramework)" />
we can probably do it for TSAPI as the otapi3 branch is on the main repo now, so i can likely get it to produce the package and push to nuget once we have an account and tokens setup.
tshock would be after this merge yeh.

2021-11-24 03:09 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <Content Include="$(OutputPath)\TerrariaServerAPI.dll" IncludeInPackage="true" Pack="true" PackagePath="lib\$(TargetFramework)" />
Kk. Sounds like I should coordinate with you about making a Pryaxis org and namespace for nuget stuff.

2021-11-24 03:18 UTC, DeathCradle commented
> 1. In order for me to approve merging it, I need to be able to build locally and test on macOS 12.0.1 (21A559) (arm64e on Rosetta), and currently, I can't do that, and I'm not quite sure why. I just kind of yolo'd this build process, though. If you have better insight on how to build, please let me know.

agreed. i will do more testing on osx/linux as time permits. possibly i need to build some initial instructions as there's a few ways to build it (cli / vs / other editors etc), and as we found out earlier they don't all work the same way. i think i just need to spend some extra time on getting it setup for all platforms correctly.

> 2. We don't have to get everything right on the merge to `otapi3` given that `general-devel` is the main branch. However, in order to merge to general-devel, most of the issues that I outlined above need to be fixed/rectified. For example, I can work on CI/tooling, or you can, but I don't want to consider that a blocker for a branch on TShock. We can easily just merge the current branch and assemble CI/releases in bits and bobs until we're happy to merge to general-devel.

yeh honestly, i wont fight you to do the CI so go nuts.
i think tsapi needs the csproj settings to generate a package, and the settings moved from AssemblyInfo like i done for tshock here so it's shared. 
feel free to use some of the otapi ci action stuff as a reference, ie for building dotnet, and uploading (not building nuget as otapi is manually done as patchers are a pain).

2021-11-26 06:09 UTC, hakusaro requested changes
I think this is for the most part the same as my previous review, but with added missing EOFs. I haven't yet tested this locally.

2021-11-26 06:09 UTC, hakusaro commented on .vscode/launch.json
> +}
Missing EOF newline, can you please add?

2021-11-26 06:09 UTC, hakusaro commented on .vscode/tasks.json
> +}
Missing EOF newline, can you please add?

2021-11-26 06:09 UTC, hakusaro commented on TShockAPI/TShock.cs
> +				var x64 = Path.Combine(Environment.CurrentDirectory, "runtimes", "win-x64");
I'm guessing this resolver needs to be updated for arm64?

2021-11-26 06:09 UTC, hakusaro commented on TShockAPI/TShockAPI.csproj
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
Fair

2021-11-26 06:15 UTC, DeathCradle commented on TShockAPI/TShock.cs
> +				var x64 = Path.Combine(Environment.CurrentDirectory, "runtimes", "win-x64");
potentially, can't say i have such a device to test with yet though. but might be able to figure something out.

2021-11-26 06:17 UTC, hakusaro commented
Quoting Death from Discord:

```bash
dotnet build TShock.sln
cd TShockAPI/bin/Debug/net5.0
dotnet ./TerrariaServerAPI.dll
```

2021-11-26 06:19 UTC, hakusaro commented
Okay, to be clear, this does at least boot on my machine, but I don't think that `dotnet ./TerrariaServerAPI.dll` is very friendly to...most people. I guess maybe it is? Is it?

2021-11-26 07:31 UTC, hakusaro commented on TShockAPI/TShock.cs
> +				var x64 = Path.Combine(Environment.CurrentDirectory, "runtimes", "win-x64");
At least with arm64, the biggest thing I'm thinking about is raspberry pi users who are using mono on rpi. I'm not sure if you have one kicking around?

2021-11-26 10:17 UTC, DeathCradle commented on TShockAPI/TShock.cs
> +				var x64 = Path.Combine(Environment.CurrentDirectory, "runtimes", "win-x64");
uh actually i do! rpi 4 model b is the best i have though, is that relevant? havent looked at these for years.

2021-11-26 18:12 UTC, hakusaro commented on TShockAPI/TShock.cs
> +				var x64 = Path.Combine(Environment.CurrentDirectory, "runtimes", "win-x64");
Yeah that works, should be valid.

2021-11-27 00:19 UTC, DeathCradle commented on .vscode/tasks.json
> +}
Sure I guess, for my own education though, why? These files can be auto generated, so not sure if new lines can be accidentally lost. I don't see us regenerating them for a while though, if anything I'd add to it.

2021-11-27 00:23 UTC, DeathCradle commented
> Okay, to be clear, this does at least boot on my machine, but I don't think that `dotnet ./TerrariaServerAPI.dll` is very friendly to...most people. I guess maybe it is? Is it?

For dev should be if you want to do it CLI style. Other than that use vs code or vs and it's 1 click. 
Release/published version is another story, but will figure that out after the above changes are done (I'll get back to these after the net6 update, which isn't far away now that I can debug the client errors making the net6 otapi release worthy)

2021-11-30 06:24 UTC, hakusaro commented
![Screen Shot 2021-11-29 at 22 23 36](https://user-images.githubusercontent.com/532647/143996466-36003a1e-fc08-4352-8617-2d861e59fb6e.png)

It's working on .NET 6 on macOS (this is under Rosetta)!

2021-11-30 07:36 UTC, hakusaro approved these changes
I'm gonna say lgtm because it runs + compiles on my machine in an easy way. Will continue to incrementally review as commits are added.

2021-12-02 05:10 UTC, hakusaro commented on .vscode/tasks.json
> +}
@DeathCradle because if they don't have newlines they don't meet the POSIX definition of a line, which will break random unix utilities in unexpected ways (e.g., they will read to the 2nd to last line and stop): https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206

2021-12-02 05:20 UTC, DeathCradle commented on .vscode/tasks.json
> +}
@hakusaro these are vscode files specifically which is why i asked, and it handles them fine on all platforms ive tested so far. (im aware of the unix stuff for other things though)
nonetheless, ill add them if i don't forget

2021-12-02 05:22 UTC, DeathCradle commented on TShockAPI/TShock.cs
> +				var x64 = Path.Combine(Environment.CurrentDirectory, "runtimes", "win-x64");
update: ive tested my rpi, and OTAPI itself runs, however ive discovered MonoMod issues where the runtime events don't -always- work, potentially JIT issues wrt runtime detours.

2021-12-02 05:54 UTC, hakusaro requested changes
Another missing newline :x

2021-12-02 05:54 UTC, hakusaro commented on TShockLauncher/TShock.sh
> +./bin/TShock.Run
Can you add a newline to this file?

2021-12-02 05:57 UTC, DeathCradle commented on TShockLauncher/TShock.sh
> +./bin/TShock.Run
done https://github.com/Pryaxis/TShock/pull/2509/commits/c159f2b388a3e084449ba089d0e11911517ec03e

2021-12-02 06:01 UTC, DeathCradle commented
> Quoting Death from Discord:
> 
> ```shell
> dotnet build TShock.sln
> cd TShockAPI/bin/Debug/net5.0
> dotnet ./TerrariaServerAPI.dll
> ```

update since launcher was added:
```shell
dotnet build TShock.sln
cd TShockLauncher/bin/Debug/net6.0
dotnet TShock.dll
```

2021-12-07 05:46 UTC, hakusaro commented
>  update: ive tested my rpi, and OTAPI itself runs, however ive discovered MonoMod issues where the runtime events don't -always- work, potentially JIT issues wrt runtime detours.

Is this still valid?

2021-12-07 06:19 UTC, hakusaro approved these changes
There's a very minor nit in here: copyright on the launcher should technically be 2021-x because it didn't exist before 2021.

The only quibble I have with the current CI output is that people aren't going to expect to download a file that contains like 7 levels deep of stuff. That can be simplified later, though, in all honesty, for public releases.

Everything else virtually lgtm. I'm not sure if I should worry or care about assembly resolving stuff + comments. I think @QuiCM is a better judge on if we should document that more.

So, lgtm. Thank you for all of your hard work on this!

I reckon we can merge this to tshock as an `otapi3` branch and then target a full release sometime around the second half of December.

![lgtm_trick](https://user-images.githubusercontent.com/532647/144976854-9af1cf2d-9141-4d2f-9fa7-b51560a4f8a2.gif)

2021-12-07 06:19 UTC, hakusaro commented on TShockLauncher/Program.cs
> +Copyright (C) 2011-2019 Pryaxis & TShock Contributors
```suggestion
Copyright (C) 2021 Pryaxis & TShock Contributors
```

2021-12-07 06:27 UTC, QuiCM approved these changes

2021-12-07 06:46 UTC, Arthri approved these changes

2021-12-07 08:18 UTC, DeathCradle commented
> > update: ive tested my rpi, and OTAPI itself runs, however ive discovered MonoMod issues where the runtime events don't -always- work, potentially JIT issues wrt runtime detours.
> 
> Is this still valid?

yes actually :c i havent been able to get back and test/debug it further. i/we also need to try other OS types on the rpi too.

2021-12-08 05:09 UTC, merged