Added "Bouncer," which prohibits the creation of large projectiles.
Pryaxis/TShock pull request #2515
Opened 2021-11-26 17:06 UTC by AgaSpace

2021-11-26 19:25 UTC, hakusaro submitted a review, later dismissed

2021-11-26 22:01 UTC, Arthri requested changes

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +		private Dictionary<short, short> Projectile_MaxValuesAI2 = new Dictionary<short, short> {
I think these should be `<short, float>` dictionaries since AI[] is an array of floats

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 405, 2 },
```suggestion
			{ 405, 1.2f },
```

Source: `Projectile.AI()`, `this.ai[1] = (float)Main.rand.Next(80, 121) / 100f;`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 405, 0 },
```suggestion
			{ 405, 0.8f },
```

Source: `Projectile.AI()`, `this.ai[1] = (float)Main.rand.Next(80, 121) / 100f;`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 410, 0 },
```suggestion
			{ 410, 0.6f },
```
Source: `Projectile.AI()`, `this.ai[1] = (float)Main.rand.Next(60, 121) / 100f;`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 410, 2 },
```suggestion
			{ 410, 1.2f },
```
Source: `Projectile.AI()`, `this.ai[1] = (float)Main.rand.Next(60, 121) / 100f;`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 612, 0 },
```suggestion
			{ 612, 0.4f },
```
Source: `Player.ItemCheck_Shoot()`, `float ai4 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f);`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 612, 2 },
```suggestion
			{ 612, 0.7f },
```
Source: `Player.ItemCheck_Shoot()`, `float ai4 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f);`
Increments every tick by `0.01`, has a lifetime of 60 for a total for +0.3. `Projectile.AI()`, `this.ai[1] += 0.01f;`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 426, 1 },
```suggestion
			{ 424, 0.8f },
			{ 425, 0.8f },
			{ 426, 0.8f },
```
Source: `Player.ItemCheck_Shoot`, `Projectile.NewProjectile(..., 0.5f + (float)Main.rand.NextDouble() * 0.3f);`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 426, 0 },
```suggestion
			{ 424, 0.5f },
			{ 425, 0.5f },
			{ 426, 0.5f },
```
Source: `Player.ItemCheck_Shoot`, `Projectile.NewProjectile(..., 0.5f + (float)Main.rand.NextDouble() * 0.3f);`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 953, 0 },
```suggestion
			{ 953, 0.85f },
```
Source: `Projectile.Kill()`, `..., 0.85f + Main.rand.NextFloat() * 1.15f);`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 756, 0 },
```suggestion
			{ 756, 0.5f },
```
Source: `Player.ItemCheck_Shoot`, `Projectile.NewProjectile(..., Main.rand.NextFloat() * 0.5f + 0.5f);`

2021-11-26 22:01 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +			{ 522, 0 }
```suggestion
			{ 522, 40f }
```
Source: `Projectile.AI()`, `if (this.ai[1] > 40f) { Kill(); }`

2021-11-27 02:36 UTC, AgaSpace commented on TShockAPI/Bouncer.cs
> +		private Dictionary<short, short> Projectile_MaxValuesAI2 = new Dictionary<short, short> {
Yes, that's much better.

2021-11-27 03:21 UTC, AgaSpace commented
The condition that checks the projectile for modified AI does not work. In fact, it works, but always. (Responds to all projectiles)

2021-11-27 11:08 UTC, Arthri approved these changes

2021-11-28 01:17 UTC, merged