Fixed exploit with cheaters ability to create custom death message
Pryaxis/TShock pull request #2521
Opened 2021-11-30 14:16 UTC by AgaSpace

2021-12-01 04:06 UTC, hakusaro requested changes
I'm not quite sure on the first check why you're checking to see if these are -1, because it seems like we should just reject this outright all the time. Can you explain the -1 checks?

2021-12-01 04:06 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +				(reason._sourcePlayerIndex == -1 || reason._sourceNPCIndex != -1 || reason._sourceOtherIndex != -1 || reason._sourceCustomReason != null))
Can you explain why these are all checking for == -1?

2021-12-01 04:06 UTC, hakusaro commented on TShockAPI/Configuration/TShockConfig.cs
> +		/// <summary>Allows you to disable or enable protection against creating custom messages with death. Created for developers who came up with a more original solution to this problem.</summary>
Is there any way to do this ingame? If not, should we just fix it and move on and not add a config option for it?

2021-12-01 04:35 UTC, Arthri commented on TShockAPI/Configuration/TShockConfig.cs
> +		/// <summary>Allows you to disable or enable protection against creating custom messages with death. Created for developers who came up with a more original solution to this problem.</summary>
No, afaict there is no way to do this in the vanilla client. However I think it would be friendlier to leave the option in, since some servers may permit/encourage the use of modified clients

2021-12-01 07:11 UTC, AgaSpace commented on TShockAPI/Bouncer.cs
> +				(reason._sourcePlayerIndex == -1 || reason._sourceNPCIndex != -1 || reason._sourceOtherIndex != -1 || reason._sourceCustomReason != null))
The constructor assigns values of -1.
When we create a "custom cause of death", we must specify the cause. Basically it is an Empty.
![image](https://user-images.githubusercontent.com/46046453/144188299-0840fe85-ec12-4da9-9728-5e7d8916ed26.png)

2021-12-01 07:12 UTC, AgaSpace commented on TShockAPI/Bouncer.cs
> +				(reason._sourcePlayerIndex == -1 || reason._sourceNPCIndex != -1 || reason._sourceOtherIndex != -1 || reason._sourceCustomReason != null))
When we kill another player, death must always be from either the player or the projectile

2021-12-01 07:14 UTC, AgaSpace commented on TShockAPI/Configuration/TShockConfig.cs
> +		/// <summary>Allows you to disable or enable protection against creating custom messages with death. Created for developers who came up with a more original solution to this problem.</summary>
I've encountered a server that uses a custom cause of death to make the death messages prettier.
I think similar servers will always appear, so I added this to the config.

2021-12-02 02:26 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +				(reason._sourcePlayerIndex == -1 || reason._sourceNPCIndex != -1 || reason._sourceOtherIndex != -1 || reason._sourceCustomReason != null))
@AgaSpace that makes sense. Can you add some or all of this as code comments above the changes?

2021-12-02 03:05 UTC, AgaSpace commented on TShockAPI/Bouncer.cs
> +				(reason._sourcePlayerIndex == -1 || reason._sourceNPCIndex != -1 || reason._sourceOtherIndex != -1 || reason._sourceCustomReason != null))
Done

2021-12-02 05:03 UTC, hakusaro approved these changes
lgtm! requesting another pair of eyes next.

![lgtm_trick](https://user-images.githubusercontent.com/532647/144361033-8b7fd744-472d-437d-8f82-630ee3e39aba.gif)

2021-12-02 06:08 UTC, QuiCM approved these changes

2021-12-02 06:59 UTC, merged