Fix item dupe via /logout & NPC (#2495 issue)
Pryaxis/TShock pull request #2522
Opened 2021-11-30 18:18 UTC by Terrarxxn

2021-12-01 04:07 UTC, hakusaro approved these changes

2021-12-01 04:07 UTC, hakusaro commented
Seems okay! Thank you for your contribution! Just need another review before we can merge this.

2021-12-01 04:13 UTC, QuiCM commented
Can't figure out how to add suggestions from mobile.

Suggesting a minor rephrasing of the error text from
```"Please close NPC window for logging out."```
To
```"Please close NPC windows before logging out"```

2021-12-01 04:17 UTC, hakusaro requested changes, later dismissed
I added the suggestion that Chris suggested, since he's on mobile.

2021-12-01 04:17 UTC, hakusaro commented on TShockAPI/Commands.cs
> +				args.Player.SendErrorMessage("Please close NPC window for logging out.");
```suggestion
				args.Player.SendErrorMessage("Please close NPC windows for logging out.");
```

2021-12-02 02:27 UTC, hakusaro commented
@Terrarxxn are you able to apply the changes that we requested todayish?

2021-12-02 04:51 UTC, Terrarxxn commented
> @Terrarxxn are you able to apply the changes that we requested todayish?

yes

2022-02-22 08:51 UTC, QuiCM commented
The changelog entry is now under the wrong release version, but happy to fix that up in post if @hakusaro doesn't mind

2022-02-22 15:44 UTC, hakusaro commented
@QuiCM sure

2022-02-23 10:22 UTC, QuiCM approved these changes

2022-02-23 10:22 UTC, merged