Corrected customDeathReason in OnPlayerDamage
Pryaxis/TShock pull request #2528
Opened 2021-12-02 15:13 UTC by AgaSpace

Previously it was called for absolutely any damage from the player.

2021-12-04 00:48 UTC, hakusaro requested changes

2021-12-04 00:48 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +			if (TShock.Config.Settings.DisableCustomDeathMessages && id != args.Player.Index &&
Can you add this to a comment explaining why this check is necessary?

Can you update the changelog?

2021-12-04 03:34 UTC, AgaSpace commented on TShockAPI/Bouncer.cs
> +			if (TShock.Config.Settings.DisableCustomDeathMessages && id != args.Player.Index &&
> Can you add this to a comment explaining why this check is necessary?
it turns out that the player sends a packet about his damage when he is hit by a npcs

2021-12-04 03:34 UTC, AgaSpace commented on TShockAPI/Bouncer.cs
> +			if (TShock.Config.Settings.DisableCustomDeathMessages && id != args.Player.Index &&
>Can you update the changelog?

It seems to me that this is unnecessary

2021-12-04 19:59 UTC, hakusaro approved these changes
![lgtm_7](https://user-images.githubusercontent.com/532647/144723001-670ae75d-14b6-4c14-b29e-6c45dd510162.gif)

2021-12-05 04:30 UTC, QuiCM approved these changes

2021-12-06 00:32 UTC, merged

2021-12-06 00:32 UTC, hakusaro commented
I merged this only because the server is virtually broken in a way without the patch. To be clear, the changelog is not optional.