Added hook for ReleaseNPC packet and anticheat for both catch and release npc
Pryaxis/TShock pull request #2535
Opened 2021-12-08 04:18 UTC by tru321

This code should stop unregistered and logged out players to catch critter and/or releasing critter by using item. Also has additional filter for ReleaseNPC to check critter being release from right item.

2021-12-08 04:53 UTC, hakusaro requested changes
I have minor suggestions, but nothing major. Everything else looks okay to me, but I haven't tested this in terms of the exploit or not.

2021-12-08 04:53 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +			if ( x >= Main.maxTilesX * 16 - 16 || x < 0 || y >= Main.maxTilesY * 16 - 16 || y < 0)
```suggestion
			if (x >= Main.maxTilesX * 16 - 16 || x < 0 || y >= Main.maxTilesY * 16 - 16 || y < 0)
```

2021-12-08 04:53 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +			if(args.Player.TPlayer.lastVisualizedSelectedItem.makeNPC != type && args.Player.TPlayer.lastVisualizedSelectedItem.placeStyle != style)
```suggestion
			if (args.Player.TPlayer.lastVisualizedSelectedItem.makeNPC != type && args.Player.TPlayer.lastVisualizedSelectedItem.placeStyle != style)
```

2021-12-08 04:53 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +				args.Player.Kick("Trying to release different critter exploit!", true);
Bouncer doesn't currently kick players that perform exploits and even in your own internal checks, you don't do this all the time. I'm not opposed to kicking players that do this, but it seems inconsistent with other anticheat we have. Do you really think we should kick players, but only in this circumstance?

2021-12-08 04:53 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +				Main.npc[npcID].active = true;
Why does this change the NPC active state if the player's changes are being rejected?

2021-12-08 04:53 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
>  			}
What even is this indentation? Why are our source files like this? :(

2021-12-08 04:53 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +		/// Called when player release a NPC,  for checking critter released from item.
```suggestion
		/// Called when player release a NPC, for checking critter released from item.
```

2021-12-08 05:49 UTC, tru321 commented
thank you for reviewing. :)
i'll check the issue one by one.

2021-12-08 06:22 UTC, tru321 commented on TShockAPI/Bouncer.cs
> +				args.Player.Kick("Trying to release different critter exploit!", true);
i wasn't sure of what to do for players in case they doing this. my option was:
1. give warn and disabling them like using banned item,
2. kicking them out of the game, or
3. ban the player.

2021-12-08 06:40 UTC, tru321 commented on TShockAPI/GetDataHandlers.cs
> +				Main.npc[npcID].active = true;
because i saw the CatchNPC code they make it inactive before sending the data. 

but after further test, it doesnt needed. :)

2021-12-08 06:40 UTC, tru321 commented on TShockAPI/GetDataHandlers.cs
>  			}
?

2021-12-08 06:42 UTC, tru321 commented on TShockAPI/Bouncer.cs
> +				args.Player.Kick("Trying to release different critter exploit!", true);
i'm starting to thinking that option 1 is suited for this case. what about you?

2021-12-08 06:43 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
>  			}
@tru321 that's not your problem but it is a problem for us

2021-12-08 06:44 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +				Main.npc[npcID].active = true;
kk, I think we can remove that unless you need it

2021-12-08 06:45 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +				args.Player.Kick("Trying to release different critter exploit!", true);
I'm honestly fine with all options. You could argue that we should just make the decision but idk. @Pryaxis/tshock might have a better idea if we should kick/ban players that break the game logic or just warn them?

2021-12-08 06:56 UTC, tru321 commented on TShockAPI/Bouncer.cs
> +				args.Player.Kick("Trying to release different critter exploit!", true);
My reference for doing this was from GetDataHandlers.HandleSyncCavernMonsterType. It kicked players who using crafted packed.

2021-12-08 06:56 UTC, tru321 commented on TShockAPI/GetDataHandlers.cs
> +				Main.npc[npcID].active = true;
at least for now, its better remove it.

2021-12-08 06:56 UTC, hakusaro commented on TShockAPI/Bouncer.cs
> +				args.Player.Kick("Trying to release different critter exploit!", true);
Fair

2021-12-09 06:56 UTC, hakusaro approved these changes, later dismissed
This just needs one more approver. lgtm!
![lgtm_trick](https://user-images.githubusercontent.com/532647/145348632-3e5f22b3-179a-4704-919a-609ee9271cf5.gif)

2021-12-09 10:25 UTC, Arthri requested changes

2021-12-09 10:25 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +				TShock.Log.ConsoleDebug("Bouncer / OnReleaseNPC rejected npc release from {0}", args.Player.Name);
I think it can be clarified here the reject was from a item <-> released npc mismatch

2021-12-09 10:25 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +				TShock.Log.ConsoleDebug("Bouncer / OnReleaseNPC rejected npc release from {0}", args.Player.Name);
I think it can be clarified here the reject was because the player is disabled

2021-12-09 10:25 UTC, Arthri commented on TShockAPI/Bouncer.cs
> +				args.Player.Kick("Trying to release different critter exploit!", true);
I think this kick message is a bit inappropriate

2021-12-09 10:27 UTC, Arthri commented on CHANGELOG.md
> +* Added filter in `GetDataHandlers.HandleCatchNpc` that stops unregistered and logged out players to catch critters. (@tru321)
This is only true if the server requires login

2021-12-10 03:03 UTC, tru321 commented
I removed some line on GetDataHandlers.HandleCatchNPC. It wasn't need to executed.

And changing the Kick message on Bouncer.OnReleaseNPC

2021-12-12 06:20 UTC, Arthri commented
Everything looks good :+1:. The only thing left now is the changelog entry about logged-out users. Afaict it doesn't prevent all logged-out users from placing critters. It only prevents it if the server requires login(via SSC or something else)

2021-12-12 11:15 UTC, tru321 commented
how about that one? i am bad at word choices.

2021-12-12 11:16 UTC, Arthri approved these changes

2021-12-12 20:34 UTC, hakusaro approved these changes

2021-12-12 20:35 UTC, merged

2021-12-12 20:35 UTC, hakusaro commented
![lgtm_7](https://user-images.githubusercontent.com/532647/145728643-a19d1f09-801b-4a77-9dac-8ad0523f5dec.gif)