Docs/protocol arthri
Pryaxis/TShock pull request #2538
Opened 2021-12-13 02:56 UTC by Arthri

- Prettify tables
- Shorten some links(`[[URL\|Name]]` -> `[[Name]]`)
- Turn packet list into table
- Normalize more headers
- some other grammatical changes

2021-12-13 02:58 UTC, hakusaro commented
Did you test/write these in Obsidian and verify that changing the links from paths won't break them? I don't think they will, but just so we're on the same page, you did, right?

2021-12-13 02:59 UTC, hakusaro commented
Also why is `N P C` spaced?

2021-12-13 02:59 UTC, Arthri commented
> Also why is `N P C` spaced?

oops, my bad. I used regex to add spaces before caps

2021-12-13 03:00 UTC, Arthri commented
> Did you test/write these in Obsidian and verify that changing the links from paths won't break them? I don't think they will, but just so we're on the same page, you did, right?

yeah, they worked

2021-12-13 03:01 UTC, hakusaro commented
> oops, my bad. I used regex to add spaces before caps

bruh

2021-12-13 03:10 UTC, hakusaro requested changes
There's at least one file that's autogenerated by TShock that's changed here, so please don't change that.

For other changes: I'll take a look in Obsidian tomorrow. I'm not opposed to the changes related to table spacing, but I feel like I need more justification as to why we should add a ton of whitespace around everything so that the table looks nice in fixed width fonts when it's rendered in non-fixed-width fonts. Markdown uses the 2nd line with the `|----|` stuff to determine the relative placement of the elements in the table. So adding space is unnecessary on other parts of the table, at least in my understanding of the language. This means that it's aesthetic changes that require more work to comply with in the long term while the docs are still being chiseled away at, imho. If you can elaborate more on why you decided to do this, I'd be less ambivalent I think.

Please try to avoid grab bag PRs like this that are size `XXL`. If you want to update the docs, please aim for size/M or lower unless you're performing a giant content update in one burst. You have multiple disparate changes in this including reformatting, content, headers, etc. This makes it extremely difficult to review. Yes, the bar is significantly lower for a wip branch, but it's still a diff that I have to read.

2021-12-13 03:10 UTC, hakusaro commented on docs/preset permission group mappings.md
> -|Permission|[[guest]]|[[default]]|[[vip]]|[[newadmin]]|[[admin]]|[[trustedadmin]]|[[owner]]|[[superadmin]]|
This file is auto generated by TShock. Please don't change it.

2021-12-13 03:10 UTC, hakusaro commented
Also, there's no PR title

2021-12-14 06:57 UTC, hakusaro approved these changes

2021-12-14 06:57 UTC, merged