1.4.4.2 on OTAPI3 and .NET 6
Pryaxis/TShock pull request #2670
Opened 2022-10-01 07:14 UTC by SignatureBeef

Currently flagged as a draft until https://github.com/Pryaxis/TSAPI/pull/212 is completed.

Same preamble as TSAPI, also note i am yet to update changelog:

This should be reviewed, with consideration to CI which will likely need some alterations.

Some plugins will break mainly due to OTAPI3 hook changes (those authors can see the [migration list here](https://github.com/SignatureBeef/Open-Terraria-API/wiki/%5Bupcoming%5D-6.-Upgrading-from-v2)), however those solely dependent on TSAPI/TShock should see essentially the same API, except needing to upgrade to net6 (help from the [upgrade assistant](https://github.com/dotnet/upgrade-assistant) but often more manual work is required).

2022-10-02 00:12 UTC, mehehe123 commented
1.4.4.2 When will it be updated?

2022-10-03 14:11 UTC, Rozen4334 commented on TShockLauncher/Program.cs
> +	var loc = Path.Combine(Environment.CurrentDirectory, "bin", arg2.Name + ".dll");
`Environment.CurrentDirectory` is the directory from which the application was started, which could be a batch file or startup script that is not home to the intended directory.

```suggestion
	var loc = Path.Combine(Path.GetDirectoryName(%(execasm)%.Location), "bin", arg2.Name + ".dll");
```

is not a perfect solution perhaps, but it will make sure that it grabs assemblies from the intended directory even when a startup file is housed elsewhere

2022-10-03 14:15 UTC, Rozen4334 commented
Running a server on this branch right now, updated and created [a number of plugins](https://github.com/Terraria-Builders-community) with relative ease. Is this PR intended as a complete update or just as an OTAPI3 update? There is a number of patches that need to be done in TShock itself, most being datahandler and bouncer related.

2022-10-03 16:14 UTC, Arthri commented on TShockAPI/TShockAPI.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
```suggestion
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
```
Laxes requirements for incremental builds, or allows Visual Studio to skip the project more

2022-10-04 06:08 UTC, SignatureBeef commented on TShockLauncher/Program.cs
> +	var loc = Path.Combine(Environment.CurrentDirectory, "bin", arg2.Name + ".dll");
im open to the suggetion, but this would likely need testing, mainly for the bundled release variant as sometimes this will have have an invalid .Location property.

2022-10-05 07:48 UTC, hakusaro reviewed
Mostly okay, minor nits. I didn't verify if the submodule was updated for TSAPI based on latest changes though.

2022-10-05 07:48 UTC, hakusaro commented on .github/workflows/ci-otapi3-legacy.yml
> +name: CI(OTAPI3) Legacy
Legacy?

2022-10-05 07:48 UTC, hakusaro commented on .vscode/launch.json
> +{
I don't use this file so I'm not reviewing it

2022-10-05 07:48 UTC, hakusaro commented on .vscode/tasks.json
> +{
This doesn't look relevant to linux/macos?

2022-10-05 07:48 UTC, hakusaro commented on CHANGELOG.md
> +## Upcoming changes (TShock 5.0.0)
This should be the only upcoming changes section -- you should remove the section below it and change this to `Upcoming changes`.

```suggestion
## Upcoming changes
```

We only kept this separate for maintaining 4 and 5 at the same time. Now we're cutting over so nbd to just call them upcoming changes.

2022-10-05 07:48 UTC, hakusaro commented on README.md
> +    <img src="https://github.com/Pryaxis/TShock/actions/workflows/ci-otapi3.yml/badge.svg" alt="GitHub Actions Build Status">
This badge won't match the legacy badge fyi. I would just change the workflow back to what it was before.

2022-10-05 07:48 UTC, hakusaro commented on README_cn.md
> +  <a href="https://ci.appveyor.com/project/hakusaro/tshock"><img src="https://ci.appveyor.com/api/projects/status/chhe61q227lqdlg1?svg=true" alt="AppVeyor Build Status"></a><a href="https://github.co
Same thing as before

2022-10-05 07:48 UTC, hakusaro commented on TShockAPI/Modules/Module.cs
> +Copyright (C) 2011-2019 Pryaxis & TShock Contributors
```suggestion
Copyright (C) 2011-2022 Pryaxis & TShock Contributors
```

2022-10-05 07:48 UTC, hakusaro commented on TShockAPI/Modules/ModuleManager.cs
> +Copyright (C) 2011-2019 Pryaxis & TShock Contributors
```suggestion
Copyright (C) 2011-2022 Pryaxis & TShock Contributors
```

2022-10-05 07:48 UTC, hakusaro commented on TShockAPI/Modules/ReduceConsoleSpam.cs
> +Copyright (C) 2011-2019 Pryaxis & TShock Contributors
```suggestion
Copyright (C) 2011-2022 Pryaxis & TShock Contributors
```

2022-10-05 07:48 UTC, hakusaro commented on TShockLauncher.Tests/GroupTests.cs
> +		Program.SavePath = ""; // 1.4.4.2
Can you add a little more context here?

2022-10-05 07:48 UTC, hakusaro commented on TShockLauncher.Tests/GroupTests.cs
> +		//Setup();
Comment?

2022-10-05 07:48 UTC, hakusaro commented on TShockLauncher/Program.cs
> +Copyright (C) 2021 Pryaxis & TShock Contributors
```suggestion
Copyright (C) 2021-2022 Pryaxis & TShock Contributors
```

2022-10-05 07:48 UTC, hakusaro commented on TShockLauncher/Program.cs
> +	var loc = Path.Combine(Environment.CurrentDirectory, "bin", arg2.Name + ".dll");
+1 to rosen's comment

2022-10-05 07:48 UTC, hakusaro commented on TShockLauncher/TShockLauncher.csproj
> +		<AssemblyName>TShock.Server</AssemblyName> <!-- TShock was initially decided on by a community poll, however tshock already exists as a folder and will clash -->
Clash?

2022-10-05 07:52 UTC, SignatureBeef commented on .github/workflows/ci-otapi3-legacy.yml
> +name: CI(OTAPI3) Legacy
legacy api, ie no DI/otapi3 branch changes.

2022-10-05 07:53 UTC, SignatureBeef commented on .vscode/launch.json
> +{
this was mighty useful when testing arm64 / monomod hooks remotely. happy to remove, or retain.

2022-10-05 07:54 UTC, SignatureBeef commented on .vscode/tasks.json
> +{
similar to launch.json. both are for VS code, not visual studio. again, happy to retain/remove.

2022-10-05 07:56 UTC, SignatureBeef commented on TShockLauncher/Program.cs
> +Copyright (C) 2021 Pryaxis & TShock Contributors
fwiw i think we need to do a project wide F&R to get everything consistent. not sure if that should be a separate PR for that (i will update this as per your suggestion since its really, a new file)

2022-10-05 07:58 UTC, SignatureBeef commented on TShockLauncher/TShockLauncher.csproj
> +		<AssemblyName>TShock.Server</AssemblyName> <!-- TShock was initially decided on by a community poll, however tshock already exists as a folder and will clash -->
yep. when tshock/server starts, it creates a tshock folder for config files. this is existing functionality, and on osx/linux, it would crash if the launcher was already called tshock.

2022-10-05 08:04 UTC, hakusaro commented on .github/workflows/ci-otapi3-legacy.yml
> +name: CI(OTAPI3) Legacy
I would just rename it to what it was before and not care about distinguishing

2022-10-05 08:05 UTC, hakusaro commented on .vscode/launch.json
> +{
I think you can keep it, idc

2022-10-05 08:05 UTC, hakusaro commented on .vscode/tasks.json
> +{
I think you can keep it; I use Sublime Text 4 on macOS.

2022-10-05 08:05 UTC, hakusaro commented on TShockLauncher/Program.cs
> +Copyright (C) 2021 Pryaxis & TShock Contributors
Technically speaking the copyright date only needs to change if it's been changed in the year that it was changed, so it's fine to tweak individually. In terms of headers, it's just always a moving target.

2022-10-05 08:05 UTC, SignatureBeef commented on TShockLauncher.Tests/GroupTests.cs
> +		Program.SavePath = ""; // 1.4.4.2
will commit something for it. for now, this is the 1.4.4.2 staticness quake and myself have been complaining about.
without these variables set to something, they are null by default, and will cause a crash due to no save paths being configured when Terraria.Main is 'touched'.
these tests are the bare minimum to get something bootstrapped essentially, without starting an actual instance of a server...at least until more tests are added!

2022-10-05 08:06 UTC, hakusaro commented on TShockLauncher/TShockLauncher.csproj
> +		<AssemblyName>TShock.Server</AssemblyName> <!-- TShock was initially decided on by a community poll, however tshock already exists as a folder and will clash -->
Right, I forgot this one!

2022-10-05 08:07 UTC, SignatureBeef commented on TShockLauncher.Tests/GroupTests.cs
> +		Program.SavePath = ""; // 1.4.4.2
DI will change these again ofc, for the better. we need to move away from staticness (glass house scenario)

2022-10-05 08:07 UTC, hakusaro commented on TShockLauncher.Tests/GroupTests.cs
> +		Program.SavePath = ""; // 1.4.4.2
Ye that makes sense, but it should be in the code or commit too, github PR is hard to find evidence for/of

2022-10-05 08:09 UTC, hakusaro commented on TShockLauncher.Tests/GroupTests.cs
> +		Program.SavePath = ""; // 1.4.4.2
Also, I believe you on DI -- but DI will be changed by Orion so ofc...

2022-10-05 08:26 UTC, SignatureBeef commented on .github/workflows/ci-otapi3-legacy.yml
> +name: CI(OTAPI3) Legacy
to confirm, back to `Build Server`? which will then align back with the README comment too.

2022-10-05 08:30 UTC, SignatureBeef commented on README.md
> +    <img src="https://github.com/Pryaxis/TShock/actions/workflows/ci-otapi3.yml/badge.svg" alt="GitHub Actions Build Status">
fyi both readme's it need t his actioned: https://github.com/Pryaxis/TShock/commit/b231bfb456882dbb11a49a4e1148f1e5d8ee57e2
want me to try reverting from history, or would you prefer me to just change them manually again?

2022-10-05 08:31 UTC, QuiCM commented on .vscode/launch.json
> +{
can confirm, vsc tasks are very handy

2022-10-05 08:35 UTC, hakusaro commented on .github/workflows/ci-otapi3-legacy.yml
> +name: CI(OTAPI3) Legacy
No, what it was before this on otapi3? (CI(OTAPI3))?

2022-10-05 08:35 UTC, hakusaro commented on README.md
> +    <img src="https://github.com/Pryaxis/TShock/actions/workflows/ci-otapi3.yml/badge.svg" alt="GitHub Actions Build Status">
manually change

2022-10-05 08:37 UTC, hakusaro commented
@SignatureBeef you can probably mark this as ready-to-review too, if you're ready

2022-10-05 08:42 UTC, SignatureBeef commented
> @SignatureBeef you can probably mark this as ready-to-review too, if you're ready

yeh will do, its basically ready aside from @Rozen4334's suggestion. this one will be a later thing, need to test it first.

2022-10-05 08:43 UTC, hakusaro submitted a review, later dismissed
![lgtm_trick](https://user-images.githubusercontent.com/532647/194018946-b0ef81e0-58d0-4527-bb06-62480049bf8c.gif)

lgtm! not quite sure if @QuiCM wants to chime in on this or abstain given that di will change stuff anyways

2022-10-05 08:44 UTC, hakusaro commented
@SignatureBeef also this doesn't backport nuget from otapi3 -- is that intentional?

2022-10-05 08:45 UTC, QuiCM submitted a review, later dismissed

2022-10-05 09:00 UTC, hakusaro requested changes
Minor nit -- can vs code automatically get with posix file standard times yet? it is 2022

2022-10-05 09:00 UTC, hakusaro commented on .github/workflows/ci-otapi3-nuget.yml
> +      run: dotnet nuget push TShockAPI/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
@SignatureBeef please add a linebreak at the end...unix...files

2022-10-05 09:02 UTC, hakusaro approved these changes, later dismissed
![lgtm_1](https://user-images.githubusercontent.com/532647/194023008-83af7b77-84c8-42ff-82fc-ce5469269daa.gif)
![lgtm_2](https://user-images.githubusercontent.com/532647/194023011-afd6a04e-8789-4117-b174-629b635dc70f.gif)
![lgtm_3](https://user-images.githubusercontent.com/532647/194023015-992867b4-731c-4391-8fd5-e27a7fbdfed3.gif)
![lgtm_4](https://user-images.githubusercontent.com/532647/194023016-577f3d43-d768-4fb6-80df-3a3cbc52554d.gif)
![lgtm_5](https://user-images.githubusercontent.com/532647/194023017-58cd6e01-9d82-4261-947b-6d9ba665d51b.gif)
![lgtm_7](https://user-images.githubusercontent.com/532647/194023019-ac26e9ac-5524-47c0-a8b8-1ab39a4fcfad.gif)
![lgtm_8](https://user-images.githubusercontent.com/532647/194023021-d952c16f-70fa-45b3-a943-70ff62c8c9ff.gif)
![lgtm_argah](https://user-images.githubusercontent.com/532647/194023025-6993fb46-baf9-4cd5-affa-a17633db8bea.gif)
![lgtm_trick](https://user-images.githubusercontent.com/532647/194023026-930de99b-eab1-4fda-9a8a-de7ca4bc3207.gif)
![lgtm](https://user-images.githubusercontent.com/532647/194023027-3002ce06-3b53-4410-b509-b9a66fd0924f.gif)

2022-10-05 09:03 UTC, hakusaro commented
@QuiCM ready 5 your review, <3

2022-10-05 09:14 UTC, SignatureBeef commented
> @SignatureBeef also this doesn't backport nuget from otapi3 -- is that intentional?

not exactly sure what you mean, but this branch imo, is more accurate than otapi3 at present. otapi3 should likely get updated from this/gen-dev once merged, i think. i need to figure out what to do with otapi3 basically, i might need to redo command services in another branch for that one, instead AIO branch and making it a mess.

2022-10-05 09:16 UTC, hakusaro commented
> not exactly sure what you mean, but this branch imo, is more accurate than otapi3 at present. otapi3 should likely get updated from this/gen-dev once merged, i think. i need to figure out what to do with otapi3 basically, i might need to redo command services in another branch for that one, instead AIO branch and making it a mess.

d/w it's too early, already resolved, etc

2022-10-05 09:42 UTC, hakusaro approved these changes

2022-10-05 09:42 UTC, merged