Fix #2674 - Change the use of current directory to match the server a…
Pryaxis/TShock pull request #2688
Opened 2022-10-06 10:26 UTC by SignatureBeef

…ssembly location

This will allow dependencies to be resolved beside the assembly as intended when startup scripts are used outside the working directory. I am not sure why or how many people would do this, as TSAPI wont load plugins (existing issue), but this is a step in the direction of opening up to allow considerations for that.

2022-10-06 18:02 UTC, hakusaro requested changes
Since this is a change in behavior can you update the changelog?

2022-10-07 05:17 UTC, SignatureBeef commented
> Since this is a change in behavior can you update the changelog?

change of behavior would be https://github.com/Pryaxis/TSAPI/pull/220 since it will change how the existing plugins are found. prior to that PR, plugins wont load if the launch script is in another location (at least in my own testing).

this one, is essentially a update to a new file since last release, and ./bin is expected to be beside the assembly in TShock 5, so this one hasnt seen a actual release yet and thus not really a change in behavior unless youre talking about pre-release builds...?

i can instead add a note for the TSAPI one, if you like? i can see the TSAPI one slipping through with autoupdates, so happy to mix in here since it's a result from looking at this one.

2022-10-07 06:43 UTC, hakusaro commented
> change of behavior would be https://github.com/Pryaxis/TSAPI/pull/220 since it will change how the existing plugins are found. prior to that PR, plugins wont load if the launch script is in another location (at least in my own testing).

that's what I mean yeah.

all PRs require changelog updates unless they're done by robots or change things that aren't related to tshock (i.e., github actions)

2022-10-07 07:08 UTC, hakusaro commented
@SignatureBeef it's merged into tshock as of 3d7ba2b2d504f4246b95bf05025a246e72c2f039, so you can update CL here

2022-10-07 08:43 UTC, hakusaro approved these changes

2022-10-07 08:44 UTC, hakusaro approved these changes

2022-10-07 08:47 UTC, merged