Add ability for items given to players to be inserted directly into their inventory instead of spawned as an item drop
Pryaxis/TShock pull request #2750
Opened 2022-10-23 03:51 UTC by pontaoski

2022-10-24 14:06 UTC, punchready commented
Beware that this can lead to item loss in case the client fills an empty slot before the packet reaches it.

2022-10-25 16:58 UTC, pontaoski commented
in practice @ penguin games we have far more cases of item loss from spawning dropped items than direct insertion. (i can't recall *any* case of direct insertion losing items, TBH)

either way, this is optional.

2022-10-25 22:43 UTC, PotatoCider requested changes
PR looks good to me. 

For the item loss issue, do you know why it happens? Couldn't that be solved by using `noGrabDelay` and `playerIndexTheItemIsReservedFor`?

2022-10-25 22:43 UTC, PotatoCider commented on TShockAPI/TSPlayer.cs
> +			GiveItemByDrop(type, stack, prefix);
Should be using overflowed `item`? 
```suggestion
			GiveItemByDrop(item.type, item.stack, item.prefix);
```

2022-10-25 22:43 UTC, PotatoCider commented on TShockAPI/TSPlayer.cs
> +			GiveItemByDrop(type, stack, prefix);
Also maybe could handle going into void vault, though that's just a nice-to-have.

2022-10-26 01:28 UTC, sowelipililimute commented
re. item loss, it's just that players aren't necessarily guaranteed to be still enough to pick up an item, even if it spawns directly on them. also, latency makes it possible for an item to spawn way off a player's current position.

2022-10-26 01:32 UTC, hakusaro commented
@pontaoski thank you for the context!

2022-10-27 21:59 UTC, hakusaro requested changes
Would you be willing to consider moving this into the SSC config instead, and then regenerating the docs with `-dump`? Since this is mostly an SSC thing, it should probably be an SSC-config thing, imho.

2022-10-28 04:20 UTC, pontaoski commented
done

2022-10-28 07:01 UTC, hakusaro commented
If I’m completely honest, the biggest problem with this is that clearly, the code is copied directly from decompiled Terraria code. While not necessarily something we’re opposed to inherently, it does pose some problems from a licensing perspective. Is there any way we can just call game methods directly instead? I haven’t looked too far into these but it doesn’t seem implausible that we can’t just tap them directly.

The other big concern is that if these methods get changed in the future, updating them becomes something that we have to know to do, and becomes subtly difficult.

I know just as much as anyone else that we used to heavily use game code like this. It wouldn’t surprise me to learn that we may have instances of this technique still laying around. But the issue is that in hindsight, and given that this is a 2022 “post-relogic DMCA world” it would probably be best if we stray away from reimplementing their methods like this.

Is there any solution you can think of that doesn’t encumber us this way? If the issue is something stupid like accessors, we could just change the accessors on the methods to be publicly callable. I’m sure this is something we could tap OTAPI for, too.

2022-10-28 08:21 UTC, PotatoCider commented
Calling the GrabItems directly and syncing the changed items could be an option. 

Another possible workaround for the item pickup would be to spawn an item with the velocity of the player, setting `noGrabDelay` to true with `playerItemIsReservedFor` set to the player's index.

2022-10-28 19:08 UTC, pontaoski commented
made the procedure more distinct from how terraria accomplishes it (but either way, algorithims/procedures themselves aren't copyrightable, just the actual manifest code itself.)

2022-10-29 00:35 UTC, merged

2022-10-29 08:04 UTC, PotatoCider commented
Sorry I didn't raise this issue further but shouldnt my suggested change be implemented? It would cause original stack of items to be dropped on the ground instead of the leftover items that had been calculated after filling the player's inventory.