Fixed SSC not save `ateArtisanBread`, `usedAegisCrystal`, `usedAegisFruit`, `usedArcaneCrystal`, `usedGalaxyPearl`, `usedGummyWorm`, `usedAmbrosia`, `unlockedSuperCart`, `enabledSuperCart` flags, and Server will correct read them.
Pryaxis/TShock pull request #2758
Opened 2022-10-24 05:30 UTC by hufang360

Fixed SSC not save `ateArtisanBread`, `usedAegisCrystal`, `usedAegisFruit`, `usedArcaneCrystal`, `usedGalaxyPearl`, `usedGummyWorm`, `usedAmbrosia`, `unlockedSuperCart`, `enabledSuperCart` flags, and Server will correct read them.

2022-10-24 14:04 UTC, punchready commented
LGTM, as far as i can see this is functionally correct

2022-10-27 08:31 UTC, hufang360 commented
Fixed Server not tracks deaths, Now players can be viewed with the `/death`, `/pvpdeath`, `/alldeath` and `/allpvpdeath` commands.

2022-10-27 21:52 UTC, hakusaro commented
@hufang360 in the future, please try to submit a PR for only one thing at a time. We can't merge this branch directly now because there's an approval for what @punchready reviewed but not a PR for the subsequent changes, which are unrelated.

2022-10-28 00:37 UTC, hufang360 commented
> @hufang360 in the future, please try to submit a PR for only one thing at a time. We can't merge this branch directly now because there's an approval for what @punchready reviewed but not a PR for the subsequent changes, which are unrelated.

OK. What can i do? 
I see the `docs/changelog.md` occur conflicts, May I resolved it?
Or other something to do?
Thank you.

2022-10-28 16:15 UTC, drunderscore requested changes
SSC changes are fine, I've review and tested them and couldn't find anything wrong.

As for the death commands, just testing out the PVE death counter something seems wrong -- if we're going to store deaths into our SSC (the database), then we should be sure to never honor the client's values, and properly respect the ones we have.

![image](https://user-images.githubusercontent.com/15949431/198684022-078e71c5-9e1c-4d25-975a-1bd0d3230c19.png)

Same complaint as particles earlier -- if this were two PRs, it would be much easier to merge the SSC changes and wait for the death changes, but now both changes are in limbo :(

2022-10-28 16:15 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> -		private static bool OnPlayerSpawn(TSPlayer player, MemoryStream data, byte pid, int spawnX, int spawnY, int respawnTimer, PlayerSpawnContext spawnContext)
Parameter names should be `lowerCamelCase`

2022-10-28 16:15 UTC, drunderscore commented on TShockAPI/Commands.cs
> +				args.Player.SendInfoMessage("There are currently no players online.");
Needs i18n

2022-10-28 16:15 UTC, drunderscore commented on TShockAPI/Commands.cs
> +				args.Player.SendInfoMessage("There are currently no players online.");
Ditto.

2022-10-28 16:31 UTC, hakusaro commented
@hufang360 this is ready-for-merge; if you don't want to you don't need to resolve conflicts as we can still merge (it's just the changelog).

The other changes that were in this PR can be merged separately, if that's okay with you!

2022-10-28 16:38 UTC, hufang360 commented
> SSC changes are fine, I've review and tested them and couldn't find anything wrong.
> 
> As for the death commands, just testing out the PVE death counter something seems wrong -- if we're going to store deaths into our SSC (the database), then we should be sure to never honor the client's values, and properly respect the ones we have.
> 
> ![image](https://user-images.githubusercontent.com/15949431/198684022-078e71c5-9e1c-4d25-975a-1bd0d3230c19.png)
> 
> Same complaint as particles earlier -- if this were two PRs, it would be much easier to merge the SSC changes and wait for the death changes, but now both changes are in limbo :(

Thanks.  The death counter seems wrong, I rollback the commit, Now it only contain one PR.

2022-10-29 00:35 UTC, merged