Update i18n
Pryaxis/TShock pull request #2760
Opened 2022-10-24 19:34 UTC by sgkoishi

https://github.com/perpetualKid/GetText.NET/issues/44

Also some minor fixes pending

2022-10-25 02:50 UTC, sgkoishi commented
There are still ~100 `player.Send(Info|Warning|Error)Message("literal string")` left.

2022-10-25 07:14 UTC, hakusaro commented
Wow that was fast

2022-10-25 07:40 UTC, hakusaro commented
This creates a few word puzzles -- I _really_ wish you'd made separate commits because it would be easier to merge smaller chunks at a time. I'm happy to approve this but I think @pontaoski should review it before it gets merged.

The reason why I was going (quite slowly) through `Commands.cs` was to try to fix the English consistency too at the same time, since it's just one pass. This doesn't change the fact that English strings aren't consistent, and if anything, makes me feel like it's a lower priority (because I won't be able justify doing it as part of the i18n work).

Like, if we merge this now and then make English consistent the strings will definitely change in i18n land. The latest Crowdin PR also has the issue with Russian, which means we can't merge more translations anyway.

2022-10-25 07:40 UTC, hakusaro approved these changes, later dismissed
(see notes)

2022-10-25 07:41 UTC, hakusaro commented
**The main thing I'm worried about is word puzzles, the rest of the PR is ok!**

2022-10-25 15:15 UTC, sowelipililimute requested changes

2022-10-25 15:15 UTC, sowelipililimute commented on TShockAPI/GetDataHandlers.cs
>  			switch (thingType)
word puzzle, each of these cases should be a complete sentence rather than combining words

2022-10-26 06:26 UTC, sgkoishi commented on TShockAPI/GetDataHandlers.cs
>  			switch (thingType)
Resolved. The `/spawnboss` and `/tree` are also kind of word puzzle: spawnboss is a total of 120 combinations and tree is a `$"Tried to grow a {lots of tree names}."`.

2022-10-27 21:48 UTC, hakusaro approved these changes

2022-10-27 21:49 UTC, hakusaro commented
I'm okay with this -- and I'm willing to say we should merge this -- but please avoid code formatting changes in bulk in future pull-requests like this. It's _really_ a lot of lines to review already.

2022-10-27 21:50 UTC, hakusaro approved these changes

2022-10-27 21:52 UTC, merged