Fixed Server not tracks deaths, Now players can be viewed with the `/death`, `/pvpdeath`, `/alldeath` and `/allpvpdeath` commands.
Pryaxis/TShock pull request #2768
Opened 2022-10-29 01:38 UTC by hufang360

Fixed Server not tracks deaths, Now players can be viewed with the `/death`, `/pvpdeath`, `/alldeath` and `/allpvpdeath` commands.

2022-11-01 05:16 UTC, hakusaro submitted a review, later dismissed
Thank you so much for your contributions! This looks good to me, but another person needs to review this besides me before merging!

2022-11-01 23:13 UTC, drunderscore requested changes
It seems like logging into a brand-new user (never before logged into) will allow the player to retain the death counter they previously had (be it from our SSC of another user after `/logout`, or the character they are joining with), instead of defaulting to `0`.

Reproduction steps:
- Execute `/user add bruh bruh default` in console
- Join server
- Execute `/login bruh bruh`
- Observe that the death counts from the joining character are preserved.

Otherwise, once the user has existed, it seems it counts properly, and logging in and out to different users properly updates the count.

2022-11-01 23:13 UTC, drunderscore commented on TShockAPI/PlayerData.cs
> +
This looks suspicious... why are only death counts that are greater than `0` allowed to override the player's data?

2022-11-02 00:14 UTC, hufang360 commented on TShockAPI/PlayerData.cs
> +
> It seems like logging into a brand-new user (never before logged into) will allow the player to retain the death counter they previously had (be it from our SSC of another user after `/logout`, or the character they are joining with), instead of defaulting to `0`.
> 
> Reproduction steps:
> 
> * Execute `/user add bruh bruh default` in console
> * Join server
> * Execute `/login bruh bruh`
> * Observe that the death counts from the joining character are preserved.
> 
> Otherwise, once the user has existed, it seems it counts properly, and logging in and out to different users properly updates the count.

Thank you so much. I'll fixed it.

2022-11-02 00:23 UTC, hufang360 commented on TShockAPI/PlayerData.cs
> +
> This looks suspicious... why are only death counts that are greater than `0` allowed to override the player's data?

Because, the `this.numberOfDeathsPVE` variable may be null, When "HandleSpawn" event can read the value is 9985.
It isn't always good, i need make change.

Refer: https://github.com/Pryaxis/TShock/pull/2758#event-7695789368

2022-11-09 01:22 UTC, hufang360 commented on TShockAPI/PlayerData.cs
> +			this.numberOfDeathsPVP = player.TPlayer.numberOfDeathsPVP;
I change this, It seems work. Can you review it agrain.

2022-11-10 07:12 UTC, hakusaro approved these changes, later dismissed

2022-11-10 07:12 UTC, hakusaro commented
@hufang360 I'm happy with this but it probably won't make 5.1, likely 5.2. This is because of the newest terraria release. Sorry.

2022-11-10 23:32 UTC, drunderscore requested changes
The issue of newly-created users inheriting the previous death count is fixed now, but something is still wrong unfortunately...

Dying will properly increment the death counter (executing `/deaths` whilst dead shows the correct number), but once the player respawns, their local death count will override the server's.

2022-11-10 23:32 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +					return true;
Dangerous change here -- when `SpawningIntoWorld` with non-matching death counts (which is likely), we will no longer call the `OnPlayerSpawn` handler, which is very much unexpected and will cause issue with plugins.

This entire check should be moved below the `OnPlayerSpawn` handler call.

2022-11-28 07:59 UTC, hakusaro commented
@drunderscore can you re-review this one?

2022-11-28 14:22 UTC, drunderscore commented
Something still isn't correct -- the same issue as above persists, where in death the counter holds the expected value, but once the player respawns, their local player's death count is respected. I've attached a video to show exactly what I'm talking about.

- Show that before login that local player has x deaths
- Login to new user
- Show new user has 0 deaths
- Die
- Before respawn, show user has 1 death
- After respawn, show user does not still have 1 death as expected.

[Screencast from 11-28-2022 09:13:16 AM.webm](https://user-images.githubusercontent.com/15949431/204299552-0f44f986-1702-4d92-9b2f-adea9b332fff.webm)

2022-12-02 22:04 UTC, sgkoishi commented
From the video, it seems that the player starts with 12544 times and ended up with 12545, which probably indicates that the client is maintaining their local count and send to the server and overwrite it. Does the server side 0-1 count ever reach the client?

2022-12-03 02:54 UTC, sgkoishi commented
> Something still isn't correct -- the same issue as above persists, where in death the counter holds the expected value, but once the player respawns, their local player's death count is respected. I've attached a video to show exactly what I'm talking about.
> 
>     * Show that before login that local player has x deaths
> 
>     * Login to new user
> 
>     * Show new user has 0 deaths
> 
>     * Die
> 
>     * Before respawn, show user has 1 death
> 
>     * After respawn, show user does not still have 1 death as expected.

The player initiates the Spawn process, and sends the local count to the server; to overwrite we need to let the server send Spawn again (double spawn!). We could initiate an extra server Spawn once per (after) login, or once per death. This might looks awkward but probably the only way 🤔

2025-05-06 11:16 UTC, sors89 commented
this might be a dumb question to ask but why don't create local variables to track player deaths instead of relying on vanilla deaths counter?

2026-02-26 09:59 UTC, ACaiCat commented
Done in #3130

2026-02-26 09:59 UTC, closed without merging