Built-in Nougat support
Pryaxis/TShock pull request #2778
Opened 2022-10-31 02:56 UTC by pontaoski

This PR allows using NuGet to simplify the management of plugins and their dependencies.

![grafik](https://user-images.githubusercontent.com/20326855/198921497-5a5419c8-9dc1-4e34-b715-93e2c368bedd.png)

2022-10-31 03:57 UTC, Arthri commented
IMO, the plugin manager code should be split into a separate executable/project

2022-10-31 14:21 UTC, pontaoski commented
the plugin manager code now lives in its own project

2022-11-01 05:49 UTC, hakusaro requested changes
Thank you for your work on this! I'm sure it will really really help in terms of getting new plugins installed for server operators in the future.

I have a few review comments. If I were to summarize my main qualms with this it's the following:

1. Internally inconsistent style. Even within only additions and only new files in this project, the code style is internally inconsistent, in terms of sheer syntactical formatting. In particular, inconsistent spacing and indentation between methods, odd spacing between individual characters, and other syntactic choices make this difficult to review.
2. Lack of support for i18n -- we just worked really hard on internationalizing TShock. There are a few edge cases, namely in TSAPI (which doesn't currently use TShock i18n stuff), but broadly, I'm happy with what we've done so far. That being said, it necessarily implies that new code should support the i18n system. If not, we're just adding more debt to pay off in the future.
3. General maintainability / future documentation needs to be improved, imho. The biggest thing to remember with TShock is that this project has been around for a long, long time. We have had maintainers come and go and entire systems become maintained by us that we have no idea how they work. For example, the entire database engine / system was written by a charismatic New Zealander who hasn't been around in...a few years. We've had to put up with this, upgrade it, maintain it, etc. for a long time. Systems like this necessarily enter the realm of "nice to have", and therefore, the maintainability requirements go up significantly. If SSC doesn't work, that's a core feature we _have_ to fix. If this doesn't work and nobody knows how to fix it, the chances of someone fixing it go down with the complexity and documentation overload. We used to have a really fancy automatic update system that would download and install and reboot TShock with updates installed. We removed that system because it was a lot of overhead/complexity to maintain and it wasn't very well-understood. This same fate will befall this system unless the code is rock solid, easily understood, and maintainable.

To elaborate more on point 3, let me recall a couple variable declaration blocks:

```csharp
		private FrameworkReducer FrameworkReducer;
		private NuGetFramework NuGetFramework;
		private ISettings Settings;
		private NuGetPathContext PathContext;
		private PackageSourceProvider PackageSourceProvider;
		private SourceRepositoryProvider SourceRepositoryProvider;
		private PackagePathResolver PackagePathResolver;
		private PackageExtractionContext PackageExtractionContext;
```

and

```csharp
			var nugetter = new Nugetter();
			var userRequests = manifest.GetPackageIdentities();
			var packagesToInstall = await nugetter.GetPackagesToInstallFor(manifest.GetPackageIdentities());
			var builtins = await nugetter.GetAllBuiltinDependencies();
			var userRoots = packagesToInstall.Where(x => userRequests.Any(y => x.Id == y.Id));
			var nonUserPackages = packagesToInstall.Where(x => !userRequests.Any(y => x.Id == y.Id));
```

In each of these instances, we "setup the world" ala COBOL or another language that supports this pattern. Then, the usages of the declared items happen significantly later and aren't super well-understood just by looking at them. I know broadly how package managers work, so I'm at an advantage here. I know what some of these words mean, and I can guess what the outputs are. But the overall control flow is opaque to a newcomer. `userRoots` _deserves_ a line or two about what a root element is and why it's important and what it's used for.

I would even support a broad architecture document that spells out, in plain English, what the high level process that this system uses is.

----

The bar for a lot of code in TShock is, unfortunately, variable. For code that isn't necessarily "core" code like what already exists, we have a relatively high bar: we want new stuff to be relatively well understood and well-patterned. This means things like documenting all public members, and even documenting private members when necessary. For existing code, like what you see in `Commands.cs`, there's a much lower barrier to entry, because we quite frankly know that we're dealing with an unwieldy beast (Terraria). The issue here is that this is entirely greenfield, and thus, there's a higher standard / barrier to entry to direct merge. I don't want to see this merged and abandoned, or merged, forgotten, and then never used. I don't want us to have to rip it all out in 5 years because it's too cumbersome to update for some reason.

On behalf of the other maintainers, I think I speak for all of them when I say that we want new code to be as clear, obvious, simple, maintainable, and consistent as possible.

Also, as an unrelated note: If you're familiar enough with git, we really prefer commits to be sensible too. For code changes, it becomes very difficult for us to find things if we have to look at the history if the commits are total chaos. For documentation and CI stuff that's really not important, but when using `git blame` commit messages ideally should have paragraphs explaining what changed and why and why it's beneficial, etc. I know that again, this is mostly greenfield, but I want to put-it-forward that it is something we care about. We just don't typically enforce these style items on some reviews (e.g., PRs that are clearly one-shots from people who can't use git), but if you can grace us with good git conventions, we'd really appreciate it too.

2022-11-01 05:49 UTC, hakusaro commented on TShockLauncher/.gitignore
> +/packages
Can you explain why you added this to gitignore?

2022-11-01 05:49 UTC, hakusaro commented on TShockLauncher/TShockLauncher.csproj
> +		<Exec Command="msgfmt --help &gt; NUL" IgnoreExitCode="True" Condition=" '$(OS)' == 'Windows_NT' ">
Can you explain why this changed?

2022-11-01 05:49 UTC, hakusaro commented on TShockLauncher/TShockLauncher.csproj
> +		<Exec Command="msgfmt --help 2&gt;/dev/null &gt;/dev/null" IgnoreExitCode="True" Condition=" '$(OS)' != 'Windows_NT' ">
Can you explain why this changed? I'm not sure I see the necessity to this.

2022-11-01 05:49 UTC, hakusaro commented on TShockLauncher/TShockLauncher.csproj
> +	<Target Name="GenerateMOFiles" DependsOnTargets="CheckMsgfmtCallable" AfterTargets="PostBuildEvent;Publish" Inputs="..\i18n\**\*.po" Outputs="$(OutDir)i18n\**\*.mo">
This change seems unrelated entirely to the other changes in this PR -- and notably, makes it harder to read.

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +				description: "Manage plugins and their requirements"
At a really high level, this is true of all the strings in this change set: I think that anything added to TShock, going forward, should be internationalized. It seems like a server operator could use most of TShock, just not the nuget-enabled TShock plugin system in their own language. But this is going to be relatively important. Can you add this support?

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +				System.Console.WriteLine("Without a list of plugins to install, I can't install any.");
In general, TShock conventionally uses third person or indirect speech / tone when speaking to users. Can you adjust the language on these strings to be more cohesive with the rest of the project?

```suggestion
				System.Console.WriteLine("Unable to install plugins without a list of plugins to install. Please supply a packages.json file to continue.");
```

To be as precise as possible: we try to avoid having the software speak as if it is a human or otherwise an intelligent agent. "Is it okay to connect to the internet?" vs "May I connect to the internet?" (in particular, I think this doesn't flow very well into other languages -- but the primary hangup is that it's tone that doesn't really exist in the project elsewhere.)

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +				System.Console.WriteLine("I had an issue reading the packages.json, because...");
```suggestion
				System.Console.WriteLine("An unexpected error occurred while reading packages.json. See exception details:");
```

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +			System.Console.WriteLine("These are the packages you asked me to install.");
```suggestion
			System.Console.WriteLine("These packages are pending installation.");
```

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +			System.Console.WriteLine("May I connect to the internet to figure out what I need to download?");
```suggestion
			System.Console.WriteLine("Connect to the internet to resolve packages?");
```

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +			do
I can't really speak to other people who wrote C# more than I do, but do people actually use do-while loops in practice? I really don't like them.

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +			catch (System.IO.FileNotFoundException)
We don't really have conventions around using directives in TShock, but I personally prefer that you throw something like `using System.IO;` in and then not fully-qualify the namespace throughout the project. The issue is that again, it just seems like a lot of work and it's extra verbosity that isn't needed, but that's just me.

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +			await nugetter.DownloadAndInstall(userRequests);
I think I need to quit C# and TShock if it means that I have to deal with async/await in this language more.

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/NugetCLI.cs
> +			Console.ForegroundColor = ConsoleColor.Green;
Can you provide a sample in a comment (e.g., ASCII in comment) that shows what this is supposed to look like?

2022-11-01 05:49 UTC, hakusaro commented on docs/changelog.md
> +* Add built-in package management capabilities for plugins
Can you move this to the new upcoming changes section?
```suggestion
* Added built-in package management capabilities for plugins. (@pontaoski)
```

2022-11-01 05:49 UTC, hakusaro commented on docs/packages.md
> +The documentation for the commands is included in the help functionality.
We're trying to provide as much functionality / documentation in docs files as possible, in order to make it easier to explain to people how things work. Can you provide command syntax, usages, and examples here, instead?

2022-11-01 05:49 UTC, hakusaro commented on docs/packages.md
> +This file primarily exists to document the `packages.json`.
Can you explain this in more layman terms for people who have no idea what this is? What does it compare to in other languages?

More broadly, when are plugins loaded from this system? How manual is this? How does it update things?

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/Nuget.cs
> +		public async Task<IEnumerable<SourcePackageDependencyInfo>> GetPackagesToInstallFor(PackageIdentity[] userRequest)
I think the preferred style is a blank line before/after all methods? Can you add these?

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/Nuget.cs
> +		public async Task<(string, PackageReaderBase)> GetOrDownloadPackage(SourcePackageDependencyInfo pkg)
In-general, we try to have XML documentation for all public methods and members. Can you add this?

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/Nuget.cs
> +		public IEnumerable<FrameworkSpecificGroup> ItemsWeCareAbout(PackageReaderBase packageReader)
Why do we care about them? Can you document this method more?

2022-11-01 05:49 UTC, hakusaro commented on TShockPluginManager/Nuget.cs
> +			FrameworkReducer  = new FrameworkReducer();
Can you consistently add only one space between things in this block of code?

2022-11-01 09:27 UTC, QuiCM commented on TShockPluginManager/Nuget.cs
> +			};
I'd like to avoid hard-coding versions if possible. Otherwise, when we update OTAPI/TSAPI/TShock we'll also have to keep version strings in sync here too

2022-11-01 14:28 UTC, pontaoski commented on TShockLauncher/TShockLauncher.csproj
> +		<Exec Command="msgfmt --help &gt; NUL" IgnoreExitCode="True" Condition=" '$(OS)' == 'Windows_NT' ">
dotnet tooling automatically poked it and i didn't notice

2022-11-01 17:00 UTC, bartico6 commented on TShockPluginManager/NugetCLI.cs
> +			do
> but do people actually use do-while loops in practice? I really don't like them.
Yes we do, for any task that requires you to do it once and then repeat it as long as a condition holds. The alternative would be to either duplicate code, or do a regular while loop with some `while(first_run || actual_condition)` gimmick.

2022-11-07 07:14 UTC, hakusaro commented
@pontaoski if you're ready to have this reviewed can you de-conflict this branch and request re-reviews from me et al?

2022-11-10 07:11 UTC, hakusaro commented
@pontaoski this will get re-reviewed, probably in 5.2 with the other PRs that are large-ish and unrelated to Terraria patch. Sorry, re-logic got us surprised again.

2022-11-27 01:37 UTC, hakusaro commented
@pontaoski can you rebase?

2022-11-28 13:17 UTC, pontaoski commented
rebased

2022-12-06 05:42 UTC, merged