update GetDataHandlers
Pryaxis/TShock pull request #2807
Opened 2022-11-06 04:34 UTC by ATFGK

#2804

2022-11-06 04:37 UTC, hakusaro commented
This doesn't compile.

2022-11-06 04:40 UTC, hakusaro requested changes
Please fix compilation errors / etc before a real review occurs

2022-11-06 04:46 UTC, punchready requested changes

2022-11-06 04:46 UTC, punchready commented on TShockAPI/GetDataHandlers.cs
> +			ai[3] = (bitsByte2[0] ? args.Data.ReadSingle() : 0f);
index should be 2 here, not 3

2022-11-06 04:46 UTC, punchready commented on TShockAPI/GetDataHandlers.cs
> +		        BitsByte bitsByte2 = bitsByte[2] ? args.Data.ReadByte() : 0;
`ReadByte` returns an `int`, not `byte`, you need to cast it first to be able to implicitly convert to `BitsByte`

2022-11-06 04:46 UTC, punchready commented on TShockAPI/GetDataHandlers.cs
> +			int projUUID = (int)(bitsByte[7] ? args.Data.ReadInt16() : -1);
i would keep the old data types here instead of casting them all to int, no need to deviate from the previous code

2022-11-06 04:46 UTC, punchready commented on TShockAPI/GetDataHandlers.cs
> +				//projUUID = -1;
no need to keep the old code, that's what git is for

2022-11-06 05:07 UTC, punchready commented on TShockAPI/GetDataHandlers.cs
> +		        BitsByte bitsByte2 = (BitsByte)(bitsByte[2] ? data.ReadByte() : 0);
just do `(byte)args.Data.ReadByte()` like the old code also did :)

2022-11-07 07:20 UTC, hakusaro requested changes
Can you...

1. Implement new data in existing hooks if you read the data of fhere?
2. Document all new fields?
3. Fix indentation (we indent using tabs instead of spaces, yes this sucks)?
4. Update the changelog so that other plugin developers know what hooks you've changed?

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +                        var cooldownCounter = (sbyte)args.Data.ReadInt8();
<img width="913" alt="Screenshot 2022-11-06 at 23 15 21" src="https://user-images.githubusercontent.com/532647/200247478-e9d54f1d-73d0-4b5f-8383-474ad53bf15d.png">

Can you fix this indentation?

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +			/// ?
Can you document this field? `?` is not sufficient documentation for this field, unfortunately.

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +                        int numberOfDeathsPVP = args.Data.ReadInt16();
Can you fix this indentation?

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +		        BitsByte bitsByte2 = (BitsByte)(bitsByte[2] ? args.Data.ReadByte() : 0);
Can you fix this indentation?

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +                        BitsByte zone5 = args.Data.ReadInt8();
Can you fix this indentation?

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +			var cw = args.Data.ReadInt8();//PaintCoatWall
You're introducing new data into this packet, but you're not actually doing anything with it. This is never used. Can you add this to the hook if you're going to read more data? e.g., `OnPaintWall(args.Player, args.Data, x, y, t, cw)`?

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +			var ct = args.Data.ReadInt8();//PaintCoatTile
Same thing as the other ones -- please add this to the hook if you're going to read more data off.

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +			sbyte random = (sbyte)args.Data.ReadInt8();
Same thing as the other ones -- please add this to the hook if you're going to read more data off.

Also is this really random? What?

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +			var npcIndex = args.Data.ReadUInt16();
Same thing as the other ones -- please add this to the hook if you're going to read more data off.

2022-11-07 07:20 UTC, hakusaro commented on TShockAPI/GetDataHandlers.cs
> +                        var cooldownCounter = (sbyte)args.Data.ReadInt8();
Same thing as the other ones -- please add this to the hook if you're going to read more data off.

2022-11-07 07:55 UTC, ATFGK commented on TShockAPI/GetDataHandlers.cs
> +			sbyte random = (sbyte)args.Data.ReadInt8();
I don't know what this is for. It's just a new one......

2022-11-07 08:31 UTC, ATFGK commented on TShockAPI/GetDataHandlers.cs
> +			sbyte random = (sbyte)args.Data.ReadInt8();
Probably related to "Rubblemaker"

2022-11-10 07:10 UTC, hakusaro commented
@ATFGK this is mostly good but it's probably not going to make the next release (5.1) due to Terraria update. I'll do a re-review soon. Thank you for your contributions -- they **will** get out eventually.

2022-11-10 11:27 UTC, closed without merging