Update GetDataHandlers.cs
Pryaxis/TShock pull request #2823
Opened 2022-11-10 11:48 UTC by ATFGK

Fixes #2804

2022-11-10 22:45 UTC, drunderscore requested changes
Just a first look, commits are a bit scattered, but there certainly are issues here that are being resolved.

I am going to ask that you remove all your changes regarding `numberOfDeathsPVE` and `numberOfDeathsPVP` -- it conflicts with #2768, which I personally would rather merge for it having been previously reviewed and supporting SSC.

2022-11-10 22:45 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +			public BitsByte Zone5 { get; set; }
Bit `0` represents the Shimmer zone

2022-11-10 22:45 UTC, drunderscore commented on docs/changelog.md
> +* Changed `GetDataHandlers.HandlePlaceObject`  added `random` but what is it used for?
Don't add questions to the `docs/changelog.md` -- you should be the one answering them.

2022-11-10 22:45 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +
Weird whitespace here

2022-11-10 22:45 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +			short numberOfDeathsPVP = args.Data.ReadInt16();
Weird whitespace at the end of these lines

2022-11-10 22:45 UTC, drunderscore commented on docs/changelog.md
> +* Changed `GetDataHandlers.HandleNpcTeleportPortal` update `npcIndex` to `int`
It was actually changed to `ushort`

2022-11-10 22:45 UTC, drunderscore commented on docs/changelog.md
> +* Changed hook `GetDataHandlers.HandleProjectileNew` added `AI[2]` Fixed #2804
I wasn't able to Bouncer to trigger with the Terra Blade on `general-devel` at c8cb747, but not reading the `ai` properly is an issue regardless. Not sure if there's a proper way to reproduce?

2022-11-10 22:45 UTC, drunderscore commented on docs/changelog.md
> +* Changed `GetDataHandlers.HandleNpcTeleportPortal` update `npcIndex` to `int`
Sign all entries with your name, end all entries with a period, and, if you are able to, try making the sentences be complete and make more sense, for example:
> Changed hook `GetDataHandlers.OnPlayerZone` _by adding_ `Zone5`

2022-11-10 22:45 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +			var cooldownCounter = (sbyte)args.Data.ReadInt8();
There's not much reason to add this if we're not going to pass it down to `OnPlayerDamage`

2022-11-10 22:45 UTC, drunderscore commented on TShockAPI/GetDataHandlers.cs
> +			sbyte random = (sbyte)args.Data.ReadInt8();
Unlike `HandlePlayerDamageV2`, I think it's alright if you don't want to pass this through, because this field was added in the middle of others, and so `direction` was being read wrong and causing issues... but it would still be cool if you did pass it through.

2022-11-11 00:03 UTC, ATFGK commented on docs/changelog.md
> +* Changed hook `GetDataHandlers.HandleProjectileNew` added `AI[2]` Fixed #2804
Terra Blade + Fire Gauntlet =100% trigger

2022-11-11 00:11 UTC, ATFGK commented
> These two parameters cause other problems related to resurrection. I hope this conflict can be resolved.

2022-11-11 00:40 UTC, ATFGK commented
> Merge his or mine first, thank you

2022-11-11 00:43 UTC, ATFGK commented
I hate to rewrite it every time I update it. Is there any easier way?

2022-11-11 01:03 UTC, drunderscore commented
> I hate having to rewrite it every time Tshock is updated. Is there any easier way?

You should be rebasing your changes on top of `general-devel` whenever there is an update, but that might be difficult sometimes, especially if you've already done a merge into your branch. You can try:

`git rebase origin/general-devel` on your branch (which is `general-devel` which isn't the best, you should checkout a branch tracking `general-devel`, but too late now).

You'll likely have conflicts in the `docs/changelog.md` file, so resolve those properly, stage the file, and then `git rebase --continue`

_Most people_ would rather just execute `git merge origin/general-devel` -- but whichever you end up doing, you're going to have conflicts with the changelog.

2022-11-11 01:08 UTC, drunderscore commented on docs/changelog.md
> +* Changed hook `GetDataHandlers.HandleProjectileNew` added `AI[2]` Fixed #2804
Awesome, can confirm this is an issue on `general-devel`, and that this PR fixes that.

2022-11-11 02:39 UTC, closed without merging