Add Shadow Candle and Brain of Confusion to `PlayerAddBuffWhitelist`, improve rejection messages
Pryaxis/TShock pull request #2827
Opened 2022-11-11 01:26 UTC by drunderscore

Fixes #2799
Fixes [issue in Discord](https://discord.com/channels/479657350043664384/479657350043664386/1040411699632672858) reported by Kojiro (which was reported to them by another individual)

2022-11-11 03:30 UTC, sgkoishi commented on TShockAPI/Bouncer.cs
> +				Reject("Target ID is over player capacity", false);
Would it be better to wrap all those `Reject` reasons with `GetString`?

2022-11-11 05:14 UTC, drunderscore commented on TShockAPI/Bouncer.cs
> +				Reject("Target ID is over player capacity", false);
Oops! Totally right, just forgot, I'll be sure to amend those :>)

2022-11-11 07:18 UTC, sgkoishi approved these changes, later dismissed

2022-11-27 01:56 UTC, hakusaro requested changes
Unless @pontaoski disagrees, I think this introduces word puzzles, and therefore, shouldn't be merged as-is. In particular, the buff reason shouldn't be interpolated blindly into the message on L1884 of Bouncer.cs -- ideally you should pass the message each time.

2022-11-27 02:11 UTC, drunderscore commented
I've updated the commit changing the log messages to not interpolate multiple sentences together. Instead, each call site now logs it's own message.

Otherwise, the rationale for that commit is the same: improve debug output to speed up triage of buff whitelist issues.

2022-11-28 01:45 UTC, ATFGK commented
"Sandstorm" and "Brand of the Inferno" will also make buff disappear

2022-11-28 07:51 UTC, merged