Fixed Super Sponge unable to absorb shimmer
Pryaxis/TShock pull request #2833
Opened 2022-11-12 01:00 UTC by sgkoishi

Fixes super sponge unable to handle shimmer, reported by [Asanay](https://ptb.discord.com/channels/479657350043664384/479657350043664386/1040757045059670026).

![image](https://user-images.githubusercontent.com/9637711/201448978-ae6d74eb-1cf8-4f91-ad30-fb88dfa5eac4.png)
![image](https://user-images.githubusercontent.com/9637711/201448970-47b92095-479a-4e24-8434-13f25bb6970c.png) (holding sponge, not picksaw)

2022-11-12 01:10 UTC, sgkoishi commented on TShockAPI/Bouncer.cs
> +				if (TShock.ItemBans.DataModel.ItemIsBanned(EnglishLanguage.GetItemNameById(selectedItemType), args.Player))
I'm not sure if the banned item check should be here, I keep it because it used to be here and the `IsBeingDisabled` check does not check item-ban disabled
https://github.com/Pryaxis/TShock/blob/5d84192624a8780bd9f35283d0f0bc1281cdb206/TShockAPI/Bouncer.cs#L1656

2022-11-12 02:05 UTC, sgkoishi commented
There is also a behaviour change here:
Previously ban lava (or other liquid) bucket => ban lava bucket, bottomless lava bucket, lava sponge, ultra sponge (if absorbing lava)
Now ban lava bucket just means lava bucket.

2022-11-28 08:09 UTC, hakusaro commented
> Now ban lava bucket just means lava bucket.

Why?

This PR is genuinely daunting to review because the implication is that the _intent_ is to "Fixed Super Sponge unable to absorb shimmer" but it also "Now ban lava bucket just means lava bucket." and in-so-doing reorders all of the code related to this and makes it hard to review. At minimum can you separate changes like this into multiple commits?

For example:

Commit A (contents) could be the diff just for absorbing shimmer
Commit B could change the behavior for the lava bucket
Commit C could reorder everything in a different way

I've looked at this PR and other PRs in TShock multiple times but it's not easy to parse or understand the change deltas with very small descriptions of changes.

2022-11-28 09:00 UTC, sgkoishi commented
Now this adds back the original behavior, ban lava bucket will disable all lava-related actions, so do water/honey/shimmer (via bottomless shimmer bucket).

2022-11-28 09:15 UTC, sgkoishi commented
The commit 49921cb seems to be confusing - view it with [`"patience diff" algorithm`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---patience) (`git diff --patience ac7ee7e..49921cb`) would be more clear:
```diff
diff --git a/TShockAPI/Bouncer.cs b/TShockAPI/Bouncer.cs
index cfa10b50..4b1ff297 100644
--- a/TShockAPI/Bouncer.cs
+++ b/TShockAPI/Bouncer.cs
@@ -1729,54 +1729,70 @@ namespace TShockAPI
 					args.Handled = true;
 				}
 
+				if (TShock.ItemBans.DataModel.ItemIsBanned(EnglishLanguage.GetItemNameById(selectedItemType), args.Player))
+				{
+					Reject(GetString("Using banned {0} to manipulate liquid", Lang.GetItemNameValue(selectedItemType)));
+					return;
+				}
+
+				switch (type)
+				{
+					case LiquidType.Water:
+						if (TShock.ItemBans.DataModel.ItemIsBanned(EnglishLanguage.GetItemNameById(ItemID.WaterBucket), args.Player))
+						{
+							Reject(GetString("Using banned water bucket without permissions"));
+							return;
+						}
+						break;
+					case LiquidType.Lava:
+						if (TShock.ItemBans.DataModel.ItemIsBanned(EnglishLanguage.GetItemNameById(ItemID.LavaBucket), args.Player))
+						{
+							Reject(GetString("Using banned lava bucket without permissions"));
+							return;
+						}
+						break;
+					case LiquidType.Honey:
+						if (TShock.ItemBans.DataModel.ItemIsBanned(EnglishLanguage.GetItemNameById(ItemID.HoneyBucket), args.Player))
+						{
+							Reject(GetString("Using banned honey bucket without permissions"));
+							return;
+						}
+						break;
+					case LiquidType.Shimmer:
+						if (TShock.ItemBans.DataModel.ItemIsBanned(EnglishLanguage.GetItemNameById(ItemID.BottomlessShimmerBucket), args.Player))
+						{
+							Reject(GetString("Using banned shimmering water bucket without permissions"));
+							return;
+						}
+						break;
+					default:
+						Reject(GetString("Manipulating unknown liquid type"));
+						return;
+				}
+
 				if (type == LiquidType.Lava && !(selectedItemType == ItemID.LavaBucket || selectedItemType == ItemID.EmptyBucket || selectedItemType == ItemID.LavaAbsorbantSponge || selectedItemType == ItemID.BottomlessLavaBucket || selectedItemType == ItemID.UltraAbsorbantSponge))
 				{
 					Reject(GetString("Spreading lava without holding a lava bucket"));
 					return;
 				}
 
-				if (type == LiquidType.Lava && TShock.ItemBans.DataModel.ItemIsBanned("Lava Bucket", args.Player))
-				{
-					Reject(GetString("Using banned lava bucket without permissions"));
-					return;
-				}
-
 				if (type == LiquidType.Water && !(selectedItemType == ItemID.WaterBucket || selectedItemType == ItemID.EmptyBucket || selectedItemType == ItemID.BottomlessBucket || selectedItemType == ItemID.UltraAbsorbantSponge || selectedItemType == ItemID.SuperAbsorbantSponge))
 				{
 					Reject(GetString("Spreading water without holding a water bucket"));
 					return;
 				}
 
-				if (type == LiquidType.Water && TShock.ItemBans.DataModel.ItemIsBanned("Water Bucket", args.Player))
-				{
-					Reject(GetString("Using banned water bucket without permissions"));
-					return;
-				}
-
 				if (type == LiquidType.Honey && !(selectedItemType == ItemID.HoneyBucket || selectedItemType == ItemID.EmptyBucket || selectedItemType == ItemID.BottomlessHoneyBucket || selectedItemType == ItemID.HoneyAbsorbantSponge || selectedItemType == ItemID.UltraAbsorbantSponge))
 				{
 					Reject(GetString("Spreading honey without holding a honey bucket"));
 					return;
 				}
 
-				if (type == LiquidType.Honey && TShock.ItemBans.DataModel.ItemIsBanned("Honey Bucket", args.Player))
-				{
-					Reject(GetString("Using banned honey bucket without permissions"));
-					return;
-				}
-
 				if (type == LiquidType.Shimmer && !(selectedItemType == ItemID.BottomlessShimmerBucket || selectedItemType == ItemID.UltraAbsorbantSponge || selectedItemType == ItemID.SuperAbsorbantSponge))
 				{
 					Reject(GetString("Spreading shimmer without holding a shimmer bucket"));
 					return;
 				}
-
-				if (type == LiquidType.Shimmer &&
-					TShock.ItemBans.DataModel.ItemIsBanned("Bottomless Shimmer Bucket", args.Player))
-				{
-					Reject(GetString("Using banned bottomless shimmer bucket without permissions"));
-					return;
-				}
 			}
 
 			if (!args.Player.HasBuildPermission(tileX, tileY))
```

2022-11-29 15:53 UTC, drunderscore requested changes
I'm not sure if this is what @hakusaro was exactly looking for when mentioning "separate commits", but I find these commits to be super weird:
- The first commit changes the magic numbers to include allow the Super Sponge
- ...but then the second commit removes those magic numbers completely
- ...but then the sixth commit totally removes all of that and replaces it with a `switch` statement on the items?

I do not recall how this PR previously looked, and that's certainly my own fault, but it's hard to imagine this is better?

2022-11-29 15:53 UTC, drunderscore commented on TShockAPI/Bouncer.cs
> +				switch (selectedItemType)
I find this entire commit to be weird... why group the check of liquids based on item instead? It just feels so backwards when looking at the code.

2022-11-29 15:53 UTC, drunderscore commented on TShockAPI/Bouncer.cs
> +				else if (selectedItemType == ItemID.BottomlessBucket)
What is even the point of this first commit, if not to just remove this entirely the next commit?

2022-11-29 15:53 UTC, drunderscore commented on TShockAPI/Bouncer.cs
>  				int selectedItemType = args.Player.TPlayer.inventory[args.Player.TPlayer.selectedItem].type;
And what's the point of this commit, if not to make all of this code a switch case later?

2022-11-29 18:57 UTC, sgkoishi commented
The first commit resolves the issue, `SuperAbsorbantSponge` and `BottomlessBucket` behave differently and we need to split them.

However, it turns out that the `bucket` number is meaningless because basically, each item maps to a bucket, e.g. `bucket == 0` is abbr of `selectedItemType == ItemID.EmptyBucket`. With `ItemID` it is more readable to have `ItemID.EmptyBucket` than `0`. This is the second commit.

After the second commit, the lines are long and there are still many duplications, e.g. we have four `EmptyBucket` and four `UltraAbsorbantSponge` checks, group them by item type helps readability: if they share common behaviour, they use the same code instead of duplicating `selectedItemType == ItemID.EmptyBucket || selectedItemType == ItemID.UltraAbsorbantSponge` or `bucket == X` four times.
https://github.com/Pryaxis/TShock/blob/536c4d25459a61971af07d03453e6d46ce7f4b41/TShockAPI/Bouncer.cs#L1815-L1817

The original commit 3e61e68 is exactly the same but in one commit and without this, (restrict all lava actions if lava bucket banned, etc. to keep the same behaviour as old implementation)
https://github.com/Pryaxis/TShock/blob/536c4d25459a61971af07d03453e6d46ce7f4b41/TShockAPI/Bouncer.cs#L1738-L1771

2022-11-29 18:58 UTC, sgkoishi commented on TShockAPI/Bouncer.cs
> +				else if (selectedItemType == ItemID.BottomlessBucket)
The first commit resolves the issue, it is standalone and can be cherry-picked.

2022-11-30 18:30 UTC, drunderscore approved these changes
I've tested that these changes fix the titled issue.

In the end, the commits will be squashed and merged into `general-devel`, so I'm alright with them staying how they are, as I was able to review the final code alright.

The `switch`ing on the selected item to check against the liquid type actually seems fine. I was a bit over-the-top with my previous dismissal of it, but the code is clean with it.

2022-11-30 18:30 UTC, drunderscore commented on TShockAPI/Bouncer.cs
> +					case LiquidType.Water:
It is a bit weird the basic bucket type being banned means the liquid is entirely banned, but that _is_ what the original code did, so that's alright I think.

2022-12-06 05:42 UTC, merged