Allow more tile and wall conversion
Pryaxis/TShock pull request #2847
Opened 2022-11-28 05:37 UTC by sgkoishi

Fixes unable to use Purification/Evil Powder in jungle, reported by [toxic](https://ptb.discord.com/channels/479657350043664384/479657350043664386/1046594200931667978).

2022-11-28 05:45 UTC, sgkoishi commented
This actually add more allowed conversion other than jungle:
`MergesWithDirtInASpecialWay` set:
```
TileID.Grass
TileID.CorruptGrass
TileID.HallowedGrass
TileID.CrimsonGrass
TileID.GolfGrass
TileID.GolfGrassHallowed
```

`JungleGrass` set:
```
TileID.JungleGrass
TileID.CorruptJungleGrass
TileID.CrimsonJungleGrass
```

`GolfGrass` set:
```
TileID.GolfGrass
TileID.GolfGrassHallowed
```
<hr>
and walls

`Dirt` set:
```
WallID.DirtUnsafe
WallID.Dirt
```

`Snow` set:
```
WallID.SnowWallUnsafe
WallID.SnowWallEcho
```

`Ice` set:
```
WallID.IceUnsafe
WallID.IceEcho
```

2022-11-28 05:58 UTC, sgkoishi commented
According to the client-side projectile AI `WorldGen.Convert(int i, int j, int conversionType, int size = 4)`, the `TileID.Sets.Conversion.Moss` and `TileID.Sets.Conversion.MossBrick` is never used by any vanilla code (perhaps we should remove them?)

2022-11-28 06:15 UTC, drunderscore requested changes
This does solve the issue of not being able to use Purification Powder on Crimson Jungle Grass. This implementation for sure seems to future-proof us much better!

2022-11-28 06:15 UTC, drunderscore commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +					UpdateServerTileState(tile, newTile, TileDataType.Tile);
Can we `break` early if this conversion is valid? I know the original code didn't, but it makes sense to do, and I believe it remains just fine and compatible with vanilla.

2022-11-28 06:15 UTC, drunderscore commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +					UpdateServerTileState(tile, newTile, TileDataType.Wall);
Ditto

2022-11-28 06:17 UTC, drunderscore commented
@sgkoishi Yeah, we should only allow the conversions that vanilla allows, being as strict and accurate as possible. A filter on the field name should suffice?

2022-11-28 08:10 UTC, hakusaro submitted a review, later dismissed

2022-12-06 05:43 UTC, hakusaro commented
@drunderscore @sgkoishi hi! I didn't merge this because @drunderscore has a change request on this PR, fyi.

2022-12-06 05:47 UTC, sgkoishi commented
Yes, it's still under consideration which impl is better. The proposed version fixed the problem and seems to be future-proof, but it actually allows certain impossible conversion (which those are harmless for now).

2022-12-10 22:11 UTC, sgkoishi commented
The wall conversion is actually way more complicated - perhaps create dummy tiles and run `WorldGen.Convert` would be better to get an 'accurate' convertible table.

2022-12-10 22:50 UTC, drunderscore approved these changes
Code looks good, field filtering is also fine.
Tested and it does fix the issues talked about in Discord.

2022-12-13 07:46 UTC, hakusaro approved these changes

2022-12-13 07:47 UTC, merged