Update GetDataHandlers.cs
Pryaxis/TShock pull request #2852
Opened 2022-11-28 13:11 UTC by ATFGK

Fixes #2804 

Fix GetDataHandlers.cs file for version 144X, and correct various errors caused by it.

2022-11-28 13:59 UTC, drunderscore commented
As originally requested in #2823, please don't include changes to number of PVE/PVP deaths, as that will be dealt with in #2768

Commits and changes are still a bit scattered, and it's not super clear which issues this PR solves -- can you update the description to include the specific issues that this PR solves?

2022-11-28 14:19 UTC, ATFGK commented
> As originally requested in #2823, please don't include changes to number of PVE/PVP deaths, as that will be dealt with in #2768
> 
> Commits and changes are still a bit scattered, and it's not super clear which issues this PR solves -- can you update the description to include the specific issues that this PR solves?

1.Fixed wrong MaxProjDamage trigger.
2.Fix the wrong resurrection prompt.
Once I delete the content related to PVE/PVP, the second problem will not be solved.

2022-11-28 14:40 UTC, drunderscore commented
@ATFGK I'm not sure I understand that last issue -- can you describe it further or show an example?

2022-11-28 15:05 UTC, ATFGK commented
> @ATFGK I'm not sure I understand that last issue -- can you describe it further or show an example?

It has little impact on "Tshock", but the wrong "SpawnContext" message will cause a lot of problems for other plug-ins because they cannot correctly recognize "SpawnContext"

2022-11-28 15:11 UTC, ATFGK commented
> > @ATFGK I'm not sure I understand that last issue -- can you describe it further or show an example?
> 
> It has little impact on "Tshock", but the wrong "SpawnContext" message will cause a lot of problems for other plug-ins because they cannot correctly recognize "SpawnContext"

"Tshock" also uses a lot of "TSPlayer. Spawn()", so other plug-ins cannot avoid receiving incorrect "SpawnContext"

2022-11-29 15:18 UTC, drunderscore commented
Yeah, totally see the issue and understand. With that other PR blocked for non-working, I'm fine accepting these changes first, even if it means the other PR will get conflicts.

I'll review this ASAP.

2022-11-29 15:28 UTC, drunderscore requested changes
All the code looks good -- just some code smell and grammatical issues otherwise!

2022-11-29 15:28 UTC, drunderscore commented on docs/changelog.md
> +* An argument `npcIndex` in `GetDataHandlers.HandleNpcTeleportPortal` has been updated to `ushort`.(@ATFGK)
These should all be placed into the past tense, starting with the verb instead:
> Added new argument(s) (description of change)...

2022-11-29 15:28 UTC, drunderscore commented on TShockAPI/Net/SpawnMsg.cs
> +		public short numberOfDeathsPVP { get; set; }
Use `UpperCamelCase` instead

2022-11-30 16:53 UTC, drunderscore requested changes
Unfortunately the changelog quality is still quite lacking -- so instead of holding this PR up for any longer due to it's non-conforming changelog, please copy the changelog entries from [this changelog file](https://github.com/drunderscore/TShock/blob/atfgk-proper-changelog/docs/changelog.md) into yours.

2022-11-30 16:55 UTC, drunderscore commented
To make it even easier, I've created a [pull request on your repository](https://github.com/ATFGK/TShock/pull/33) for this branch with the correct changes.

2022-12-01 02:16 UTC, ATFGK commented
> To make it even easier, I've created a [pull request on your repository](https://github.com/ATFGK/TShock/pull/33) for this branch with the correct changes.

Thank you very much for your help. :-D

2022-12-06 05:45 UTC, merged