Fixed docker builds for arm64 and updated docker documentation
Pryaxis/TShock pull request #2899
Opened 2023-01-16 00:24 UTC by yeraylopez

Might need @PotatoCider to review changes in .dockerignore for the possibility that dependencies are added in the future.

2023-01-16 14:33 UTC, PotatoCider approved these changes
Looks good to me.

2023-03-10 01:38 UTC, hakusaro commented
What broke with `--platform`?

2023-03-10 14:44 UTC, PotatoCider commented
IIRC, he couldn't build an arm64 image on his Raspberry Pi. You can refer to the discord conversation we had here: https://discord.com/channels/479657350043664384/711282444933791774/1064342428674445424

2023-04-05 11:26 UTC, visualwind reviewed
It works

2023-07-29 17:40 UTC, pmnlla commented
Should this be merged yet?

2023-09-29 14:28 UTC, PotatoCider requested changes
Hey, I've taken another fresh look at this PR and our conversation months earlier. I realised that the documentation is probably correct in the first place. 

This is because you shouldn't be using `docker buildx` to build images ***on*** `arm64` ***for*** `arm64`, but ***on*** `amd64` ***for*** `arm64`. The correct way is to simply use `docker build --build-arg TARGETPLATFORM=linux/arm64 .`

Sorry about the confusion! I could take over this PR if you want :).

2023-09-29 14:28 UTC, PotatoCider commented on docs/docker.md
> +sudo docker buildx build -t tshock:linux-arm64 --build-arg TARGETPLATFORM=linux/arm64 --load .
```suggestion
sudo docker buildx build -t tshock:linux-arm64 --platform linux/arm64 --load .
```

2025-01-27 00:46 UTC, hakusaro commented
@PotatoCider is this still relevant given the recent docker changes?

2025-01-27 01:22 UTC, PotatoCider commented
Nope not relevant. The changes in `.dockerignore` are no longer needed, and the documentation is already correct. The only valid change is in the `Dockerfile`, which logs the platforms supported if an unsupported platform is provided.

2025-01-27 09:58 UTC, hakusaro commented
Closing in lieu of the new wiki and related docker changes

2025-01-27 09:58 UTC, closed without merging