Rewrite STR handling
Pryaxis/TShock pull request #2936
Opened 2023-04-04 03:53 UTC by punchready

The old handler had a pretty significant flaw allowing you to basically bypass most checks, so I went to rewrite it completely.
All categories of checks have been tested successfully, but I did not perform exhaustive checks for every potential action due to lack of time, so if needed someone could do that based on the list of operations in the code.
While writing this it also became apparent again that tShock does not have a way to restrict wall placement like it does with tiles, which would matter during biome conversion handling.

2023-04-20 14:07 UTC, QuiCM requested changes
Rewriting Terraria code to protect against its own exploits makes me cry, but it is what it is.

Only real change I'd like is the removal of the existing `SendTileRectHandler`, and rename this to take its place

2023-04-20 14:12 UTC, punchready commented
Yeah I wanted to avoid making the diff unreadable, which at the very least requires a different file name which would also suck. I guess I can change the class name after everyone has had a chance to check it out while the diff is still clean.

2023-06-06 10:52 UTC, QuiCM commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +									// this is the only tile type sent in a tile rect where the frame have a different pattern (56, 74, 92 instead of 54, 72, 90)
Is there a separate check for this particular case? Does there need to be one?

2023-06-06 10:54 UTC, QuiCM commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +						if (Main.tile[x, y].active() && !(Main.tile[x, y].type != TileID.RollingCactus && (Main.tileCut[Main.tile[x, y].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[x, y].type])))
Why is rolling cactus special? A comment would help clarify why this particular set of logic is necessary

2023-06-06 10:59 UTC, QuiCM approved these changes, later dismissed

2023-06-06 10:59 UTC, QuiCM commented
Couple minor Qs, but overall I'm happy to trust that this works

2023-06-06 11:04 UTC, punchready commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +									// this is the only tile type sent in a tile rect where the frame have a different pattern (56, 74, 92 instead of 54, 72, 90)
The check being referred to is right below the comment?

2023-06-06 11:06 UTC, punchready commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +						if (Main.tile[x, y].active() && !(Main.tile[x, y].type != TileID.RollingCactus && (Main.tileCut[Main.tile[x, y].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[x, y].type])))
This is from `TileObject.Place` but actually the client will kill those tiles manually before sending that, so not sure why i kept that in, will remove in a minute.

2023-06-06 11:10 UTC, QuiCM commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +									// this is the only tile type sent in a tile rect where the frame have a different pattern (56, 74, 92 instead of 54, 72, 90)
Gotcha. Tired brain + Terraria logic does not a good combination make.






I hate tile logic

2023-06-06 16:36 UTC, Arthri requested changes

2023-06-06 16:36 UTC, Arthri commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +						if (Type is MatchType.Placement or MatchType.StateChange)
`StateChange` seems to have a duplicate check for this in `MatchStateChange`. And Removal seems to implement it separately

2023-06-06 16:36 UTC, Arthri commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +			if (args.Width > 4 || args.Length > 4)
The client sends a 5x5 SendTileSquare for beds and bathtubs in `PlaceThing_Tiles_PlaceIt_SpinBedsAndBaths`. I think there's a 1x6 in `ToggleLampPost`, though I am unsure if this is reachable client code. `HitSwitch` implies it is

2023-06-06 16:36 UTC, Arthri commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +				MatchesConversionSpread(args.Player, rect) ||
This check seems to happen twice, there's another one above

2023-06-06 17:12 UTC, Arthri commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +			if (args.Width > 4 || args.Length > 4)
Nevermind, upon further analysis, neither are true. `TripWire` prevents the latter case from happening, and all beds and bath tubs do not trigger `PlaceThing_Tiles_PlaceIt_SpinBedsAndBaths` at the moment

2023-06-06 17:12 UTC, Arthri submitted a review, later dismissed

2023-06-07 00:53 UTC, punchready commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +			if (args.Width > 4 || args.Length > 4)
Explicit rotation on placement is a legacy implementation, in 1.4 rotation is handled based on the player's direction. The other STR cases are only sent by the server, mostly from wiring toggles as you noted.

2023-06-07 01:00 UTC, punchready commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +						if (Type is MatchType.Placement or MatchType.StateChange)
The check in `Matches` verifies the tile data that is incoming (`TileRect[x, y]`), the checks in `MatchPlacement` etc. verify the target tiles (`Main.tile[x, y]`).

2023-06-07 03:02 UTC, Arthri commented on TShockAPI/Handlers/SendTileRectHandler.cs
> +						if (Type is MatchType.Placement or MatchType.StateChange)
Ah I see, I missed that

2023-06-07 03:03 UTC, Arthri approved these changes

2023-08-15 09:51 UTC, merged