Changes to PlayerData, NetItem, TSPlayer and hooks
Pryaxis/TShock pull request #2940
Opened 2023-05-01 10:38 UTC by AgaSpace

2023-05-01 23:02 UTC, sgkoishi commented
*Plugins that use `TSPlayer.DamagePlayer` or `KillPlayer` requires recompile (source level compatible).*
*Plugins that use `TShockAPI.Hooks.PlayerHooks.OnPlayerCommand` requires change.*

2023-05-02 03:26 UTC, punchready requested changes
- The `OnAccountGroupChange` hook should be invoked in `UserManager.SetUserGroup` instead, right now it only fires when a group gets changed via command
- The `PlayerCommand` hook should probably be kept and called like it was before for binary backwards compatibility
- The `UpdateSection` method's `visibility` parameter should be called something like `isLoaded` instead to not be misleading, and the documentation adjusted
- The `DamagePlayer` and `KillPlayer` reason parameters should also be put into an overload instead for binary backwards compatibility

2023-05-02 09:20 UTC, AgaSpace commented
> * The `OnAccountGroupChange` hook should be invoked in `UserManager.SetUserGroup` instead, right now it only fires when a group gets changed via command
> * The `PlayerCommand` hook should probably be kept and called like it was before for binary backwards compatibility
> * The `UpdateSection` method's `visibility` parameter should be called something like `isLoaded` instead to not be misleading, and the documentation adjusted
> * The `DamagePlayer` and `KillPlayer` reason parameters should also be put into an overload instead for binary backwards compatibility

I wrote it down as you instructed

2023-05-02 12:48 UTC, punchready requested changes

2023-05-02 12:48 UTC, punchready commented on TShockAPI/TSPlayer.cs
> +				damage, (new Random()).Next(-1, 1), false, false, 0, -1, -1);
This should call the second overload with the default reason.

2023-05-02 12:48 UTC, punchready commented on TShockAPI/TSPlayer.cs
> +				99999, (new Random()).Next(-1, 1), false, -1, -1);
Same here; call the second overload.

2023-05-02 12:48 UTC, punchready commented on TShockAPI/TSPlayer.cs
> +		/// <param name="withMsg">Is it necessary to send a message about changing pvp mode</param>
The grammar is slightly off, "Whether a chat message about the change should be sent." would be better.

2023-05-02 12:48 UTC, punchready commented on TShockAPI/Hooks/PlayerHooks.cs
> +			args = playerCommandEventArgs.CommandArgs;
This line is probably supposed to be after the hook invocation.

2023-05-02 12:48 UTC, punchready commented on TShockAPI/DB/UserManager.cs
> +			if (AccountHooks.OnAccountGroupUpdate(account, author, ref grp))
This is not how an account update hook should be implemented:
- This still doesn't get invoked when a plugin changes a user's group with the other overload
- This gets invoked after the change has already been made in the database, not allowing proper cancellation
- This throws if canceled?? It should probably either not be cancelable or have a clear return value indicating whether the change was canceled, or cancel by setting the group to the previous group of the user silently

2023-05-02 12:48 UTC, punchready commented on TShockAPI/Hooks/AccountHooks.cs
> +		public UserAccount Account { get; private set; }
This event should either only give the user account name or ensure that a full account instance has been fetched to not be confusing to consumers.

2023-05-02 13:07 UTC, AgaSpace commented on TShockAPI/Hooks/AccountHooks.cs
> +		public UserAccount Account { get; private set; }
> This event should either only contain a user account name field or ensure that a full account instance has been fetched to not be confusing to consumers.

Should I rename the next property to "AccountName" or should I leave it as it was, which is "Account"?

2023-05-02 13:09 UTC, punchready commented on TShockAPI/Hooks/AccountHooks.cs
> +		public UserAccount Account { get; private set; }
`string AccountName` or `UserAccount Account`

2023-05-09 04:45 UTC, AgaSpace commented
@punchready, Any other changes needed for the merge?

2023-05-09 10:37 UTC, punchready requested changes
Account group change event needs to be reworked, otherwise LGTM.

2023-05-09 10:37 UTC, punchready commented on TShockAPI/DB/UserManager.cs
> +				throw new ArgumentException("The hook blocked the change of the user group.");
This should throw a custom exception class at least.

2023-05-09 10:37 UTC, punchready commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
Again, an account group update event is quite pointless if it only fires when changing a group via command and not from all other calls to the `SetUserGroup` method.

2023-05-10 02:40 UTC, AgaSpace commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
Then I need to specify that Author can be null (that is, I will add documentation to the Author property that explains this) and then add a hook call to the SetUserGroup overload?

2023-05-10 08:42 UTC, punchready commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
I would make an abstract `AccountGroupUpdateEventArgs` base class and then have a class for plugin-initiated events like `AccountGroupUpdateByPluginEventArgs` and one for player-initiated events like `AccountGroupUpdateByPlayerEventArgs`.

2023-05-10 08:58 UTC, AgaSpace commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
> I would make an abstract `AccountGroupUpdateEventArgs` base class and then have a class for plugin-initiated events like `AccountGroupUpdateByPluginEventArgs` and one for player-initiated events like `AccountGroupUpdateByPlayerEventArgs`.

Do I need to pass `TerrariaPlugin` to `AccountGroupUpdateByPluginEventArgs`?

2023-05-10 09:00 UTC, punchready commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
That's probably too much effort for too little use cases.

2023-05-10 09:13 UTC, sgkoishi commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
Account group update can only be triggered by either `/user` with `tshock.superadmin.user` permission - superadmin, server console, or plugin. Maintainers can access the database and bypass the hook, and so do the plugins.
What's the use case of this hook instead of using MonoMod?

2023-05-10 09:20 UTC, AgaSpace commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
> Account group update can only be triggered by either `/user` with `tshock.superadmin.user` permission - superadmin, server console, or plugin. Maintainers can access the database and bypass the hook, and so do the plugins. What's the use case of this hook instead of using MonoMod?

Are you saying that it would still be better to keep 1 class `AccountGroupUpdateEventArgs`?

2023-05-10 09:56 UTC, sgkoishi commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
> Are you saying that it would still be better to keep 1 class `AccountGroupUpdateEventArgs`?

At least it is confusing for me to tell which is the initiator if the plugins are chained together.

<hr>

If a plugin dev wants to be triggered when `SetUserGroup`, they can just go this (without this PR) - the whole group change event is like saving three lines of code
```csharp
using TShockAPI.DB;

new MonoMod.RuntimeDetour.Hook(
    () => TShock.UserAccounts.SetUserGroup(null, null), 
    (Action<UserAccountManager, UserAccount, string> originalSetGroup, UserAccountManager mgr, UserAccount acc, string a) => {
        Console.WriteLine("Before the group change");
        if (happyEnough && goodLuck)
        {
            originalSetGroup(mgr, acc, a);
        }
        Console.WriteLine("After the group change");
    });
```

2023-05-10 11:31 UTC, AgaSpace commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
@sgkoishi, In this way, you can do everything at all. Then why do we need other hooks?
I mean, our way would be more convenient.

2023-05-13 13:47 UTC, AgaSpace commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
@sgkoishi Generally speaking, do you want me to add `MonoMod.RuntimeDetour.Hook` to the SetUserGroup method? Then how do I pass the "author" of that action?

2023-05-13 17:50 UTC, sgkoishi commented on TShockAPI/Hooks/AccountHooks.cs
> +		public TSPlayer Author { get; private set; }
I would say the current version is quite ok and enough - the MonoMod one can provide post-event but I couldn't see much usage of it, it really doesn't matter that much if something happens right before/after a group change. The only required thing I think is the pre-event that can cancel it.

2023-05-14 01:52 UTC, closed without merging

2023-05-14 01:52 UTC, AgaSpace commented
Since I have been asked to split this PR into several smaller PRs, I am closing this PR.