Fix dump-reference-data mutate command name
Pryaxis/TShock pull request #2943
Opened 2023-05-13 10:57 UTC by sgkoishi

![dump-reference-data](https://github.com/Pryaxis/TShock/assets/9637711/044ca026-151d-4045-b0fb-0423a84149d4)

2023-05-13 11:05 UTC, Arthri requested changes

2023-05-13 11:05 UTC, Arthri commented on TShockAPI/Permissions.cs
> +					: c.Name);
```suggestion
					? $"/{c.Name} (/{string.Join(" /", c.Names.Skip(1))})"
					: $"/{c.Name}");
```

2023-05-13 12:08 UTC, Arthri submitted a review, later dismissed

2023-06-06 11:17 UTC, QuiCM submitted a review, later dismissed

2025-01-25 12:30 UTC, hakusaro approved these changes

2025-01-25 12:34 UTC, merged