NetItem changes
Pryaxis/TShock pull request #2945
Opened 2023-05-14 03:45 UTC by AgaSpace

2023-06-06 10:40 UTC, Arthri commented on TShockAPI/NetItem.cs
> +		public Item Build()
In my opinion, `ToItem` or something else would be more descriptive. "Build"ing a NetItem isn't very descriptive in of itself

2023-06-06 12:16 UTC, AgaSpace commented on TShockAPI/NetItem.cs
> +		public Item Build()
> In my opinion, `ToItem` or something else would be more descriptive. "Build"ing a NetItem isn't very descriptive in of itself

Done

2023-06-07 16:25 UTC, Arthri submitted a review, later dismissed

2023-06-08 09:23 UTC, punchready requested changes

2023-06-08 09:23 UTC, punchready commented on docs/changelog.md
> +  * Added the `Build` method to get a copy of `Terraria.Item`.
Needs to be updated to `ToItem`

2023-06-08 09:23 UTC, punchready commented on TShockAPI/NetItem.cs
> +				throw new Exception("It is impossible to create an item whose ID is 0.");
That is not true, and this method should allow creating an empty item in my opinion, in case that is useful to some plugins.

2023-06-08 10:36 UTC, Arthri submitted a review, later dismissed

2023-06-08 10:36 UTC, Arthri commented on TShockAPI/NetItem.cs
> +		/// <exception cref="Exception">If the item ID is 0.</exception>
```suggestion
```
This comment is obsolete

2023-06-08 10:36 UTC, Arthri commented on docs/changelog.md
> +  * In the constructor I added optional parameters `stack` and `prefix`.
In my opinion, this implies the existence of new parameters. I think something like "`stack` and `prefix` are now optional parameters" would be better

2023-06-08 12:03 UTC, punchready approved these changes

2023-06-08 12:04 UTC, Arthri submitted a review, later dismissed

2023-06-17 18:02 UTC, Arthri approved these changes

2025-01-26 00:06 UTC, merged