Docker Compose example
Pryaxis/TShock pull request #2991
Opened 2023-11-27 01:04 UTC by ramidzkh

`docker run` explicitly isn't very nice, so I wrote a compose file for myself today and why not share it

2023-11-27 13:06 UTC, lucasgames8957 requested changes
If you already contributed do not add your name to the contributors but you have to add your changes to the changelog either way

2023-11-28 13:11 UTC, lucasgames8957 commented
Thank you @ramidzkh
Please review this @hakusaro

2023-12-08 02:54 UTC, ramidzkh commented
CC @PotatoCider since you seem to be familiar with Docker here

2023-12-08 15:20 UTC, lucasgames8957 commented
aah

2023-12-09 02:51 UTC, PotatoCider approved these changes
Yep, LGTM.

2025-01-26 00:21 UTC, hakusaro commented
I added this example to the new wiki since we're moving everything there anyways, thank you for your contributions!

2025-01-26 00:21 UTC, closed without merging

2025-01-26 01:03 UTC, ramidzkh commented
FYI the `version: "3"` line is now deprecated

2025-01-26 01:18 UTC, hakusaro commented
@ramidzkh the beauty of the wiki is that you can update it!

2025-01-26 01:18 UTC, hakusaro commented
https://github.com/Pryaxis/TShock/wiki/docker