fix: /help, /me, and /p commands can't work in non-English languages
Pryaxis/TShock pull request #3039
Opened 2024-07-31 11:47 UTC by ACaiCat

### When TShock runs in a non-English language, vanilla commands prefix will be localized.
eg.(Chinese) `/help` (English command prefix) => `/帮助`  (Chinese command prefix) 

### `TShock.OnChat` cannot correctly handle vanilla command prefixes
e.g.(Chinese) When a player use `/help`, TShock will execute `/帮助` (causing the command to not be found).
![image](https://github.com/user-attachments/assets/8db23ed1-9b08-4f90-91c9-6eb12a822096)

> Invalid command entered. Type /help for a list of valid commands.

### This PR add `EnglishLanguage.GetCommandPrefixByName` to get English vanilla command prefix.
![image](https://github.com/user-attachments/assets/73318f23-1179-4a46-9473-c79d52c22863)

2024-07-31 12:25 UTC, ACaiCat commented
Solve #2914

2024-10-26 11:10 UTC, ACaiCat commented
Could someone review this PR?

2024-10-26 12:18 UTC, hakusaro approved these changes

2024-10-26 12:19 UTC, hakusaro commented
Can someone else look at this too?

2024-10-28 12:45 UTC, Arthri requested changes

2024-10-28 12:45 UTC, Arthri commented on TShockAPI/Localization/EnglishLanguage.cs
> +				ChatManager.Commands._localizedCommands.Clear();
This line effectively disables TShock processing Terraria commands, because TShock uses `_localizedCommands` here https://github.com/ACaiCat/TShock/blob/7419205548fb9779f83bc924222c1df9741ddff5/TShockAPI/TShock.cs#L1494

2024-10-28 12:45 UTC, Arthri commented on TShockAPI/Localization/EnglishLanguage.cs
> +				foreach (var command in ChatManager.Commands._localizedCommands)
This doesn't seem to request the English localization?

2024-10-28 16:00 UTC, sgkoishi commented
This is requesting the enUS locale as set earlier
https://github.com/Pryaxis/TShock/blob/0b6bf9ef4050f39f468d6782ea2992d8ce82e8bb/TShockAPI/Localization/EnglishLanguage.cs#L50

I guess the `Clear` was done for similar reason like my implementation (but I did set the `_localizedCommands` back after)
https://github.com/sgkoishi/yaaiomni/blob/debf82951dd84bd307fc7bce06a1c03160479976/Core/Enhancements.cs#L129

2024-10-29 13:57 UTC, sgkoishi commented on TShockAPI/Localization/EnglishLanguage.cs
> +				ChatManager.Commands._localizedCommands.Clear();
Just double checked and this Clear happened right before vanilla `Main.Initialize`, and it was empty before we call `ChatInitializer.Load`.

2024-10-29 17:32 UTC, bartico6 commented
> Can someone else look at this too?

I would, but I don't understand the issue very well.. Can you ELI5 what is wrong?

2024-10-30 01:50 UTC, sgkoishi commented
> > Can someone else look at this too?
> 
> I would, but I don't understand the issue very well.. Can you ELI5 what is wrong?

Terraria will translate chat commands into command id. TShock translate them back to keep the command working.
However, when the server and the client have different locale, a `enUS` player send `/help` will be sent as `CommandId: Help` and a `deDE` server will translate it back to `/hilfe`, thus the command is broken.

2024-10-30 14:25 UTC, Arthri approved these changes
Tested and can confirm that it works as intended

2025-01-26 00:44 UTC, merged